# Generated by Django 5.2.17 on 2026-09-01 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('students', 'Students'), ('attendance', 'Attendance')], max_length=12, verbose_name='kind')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='rows read')),
                ('valid_count', models.PositiveIntegerField(default=0, verbose_name='rows that would apply')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='rows with problems')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='records created')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='records updated')),
                ('status', models.CharField(choices=[('preview', 'Awaiting confirmation'), ('confirmed', 'Applied'), ('rejected', 'Discarded'), ('failed', 'Failed validation')], default='preview', max_length=10, verbose_name='status')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='report')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='class_sessions.classsession')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bulk import',
                'verbose_name_plural': 'bulk imports',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['kind', 'status'], name='bulkimport_kind_status_idx')],
            },
        ),
    ]
