# Generated by Django 5.2.17 on 2026-09-06 18:11

import apps.reporting.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Set when the record was removed. Null means live.",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "delete_reason",
                    models.CharField(
                        blank=True,
                        help_text="Why it was removed. Shown on the recovery screen.",
                        max_length=255,
                        verbose_name="reason for deletion",
                    ),
                ),
                (
                    "report_key",
                    models.CharField(
                        max_length=40,
                        validators=[apps.reporting.models.validate_report_key],
                        verbose_name="report",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("xlsx", "Excel"), ("pdf", "PDF")],
                        max_length=4,
                        verbose_name="format",
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict, verbose_name="filters")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True, verbose_name="queued at")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="started at"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="finished at"),
                ),
                ("row_count", models.PositiveIntegerField(default=0, verbose_name="rows written")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to=apps.reporting.models.export_upload_to,
                        verbose_name="file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, verbose_name="original filename"),
                ),
                ("checksum", models.CharField(blank=True, max_length=64, verbose_name="SHA-256")),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="size in bytes"),
                ),
                ("error", models.CharField(blank=True, max_length=500, verbose_name="error")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expires at"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who removed it. Null if the account has since been removed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "export job",
                "verbose_name_plural": "export jobs",
                "ordering": ("-created_at",),
                "abstract": False,
                "base_manager_name": "all_objects",
                "indexes": [
                    models.Index(
                        fields=["requested_by", "-created_at"], name="exportjob_owner_idx"
                    ),
                    models.Index(fields=["status", "-created_at"], name="exportjob_status_idx"),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
