# Generated by Django 5.2.17 on 2026-09-16 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_exportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen', models.CharField(max_length=60, verbose_name='screen')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('filters', models.JSONField(default=dict, verbose_name='filters')),
                ('user', models.ForeignKey(help_text='The only person who may see or delete this row.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved filter',
                'verbose_name_plural': 'saved filters',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'screen'], name='saved_filter_user_screen_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'screen', 'name'), name='saved_filter_user_screen_name_unique')],
            },
        ),
    ]
