# Generated by Django 5.2.17 on 2026-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0003_savedfilter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("processing", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="queued",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
