# Generated by Django 5.2.17 on 2026-08-31 20:32

import apps.common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_code_sequence'),
        ('trainers', '0002_trainer_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Human-readable identifier, e.g. GRS-B-00021. Allocated by the system.', max_length=20, unique=True, verbose_name='batch code')),
                ('name', models.CharField(help_text='For example: Linux Foundations — Morning, Jan 2026.', max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='description')),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of students holding a seat.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='capacity')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='upcoming', max_length=20, verbose_name='status')),
                ('course', models.ForeignKey(help_text='Protected: deleting a course with batches would orphan its students.', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, help_text='The trainer who teaches this batch. Set before the batch goes active.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'ordering': ('-start_date', 'code'),
            },
        ),
        migrations.CreateModel(
            name='BatchSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, verbose_name='day')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('timezone_name', models.CharField(default='Asia/Kolkata', help_text='IANA name, e.g. Asia/Kolkata.', max_length=64, verbose_name='time zone')),
                ('location', models.CharField(blank=True, help_text='Classroom, lab or meeting link label. A placeholder for now.', max_length=150, verbose_name='location')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Turn off to suspend a slot without losing its history.', verbose_name='active')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='batches.batch')),
                ('trainer', models.ForeignKey(blank=True, help_text='Defaults to the batch trainer. Set to cover a single slot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'batch schedule',
                'verbose_name_plural': 'batch schedules',
                'ordering': ('weekday', 'start_time'),
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['course', 'status'], name='batch_course_status_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['trainer', 'status'], name='batch_trainer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status', 'start_date'], name='batch_status_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='batch_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='batch_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='batchschedule',
            index=models.Index(fields=['batch', 'weekday'], name='schedule_batch_day_idx'),
        ),
        migrations.AddIndex(
            model_name='batchschedule',
            index=models.Index(fields=['trainer', 'weekday'], name='schedule_trainer_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='batchschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_end_after_start'),
        ),
    ]
