# Generated by Django 5.2.17 on 2026-09-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_code_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='delivery_mode',
            field=models.CharField(choices=[('offline', 'In the classroom'), ('online', 'Online'), ('hybrid', 'Both')], default='offline', help_text='How this cohort is taught. A student may differ; see Enrollment.', max_length=10, verbose_name='delivery mode'),
        ),
    ]
