# Generated by Django 5.2.17 on 2026-09-06 17:45

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_delivery_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'base_manager_name': 'all_objects', 'ordering': ('-start_date', 'code'), 'verbose_name': 'batch', 'verbose_name_plural': 'batches'},
        ),
        migrations.AlterModelOptions(
            name='batchschedule',
            options={'base_manager_name': 'all_objects', 'ordering': ('weekday', 'start_time'), 'verbose_name': 'batch schedule', 'verbose_name_plural': 'batch schedules'},
        ),
        migrations.AlterModelManagers(
            name='batch',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='batchschedule',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='delete_reason',
            field=models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion'),
        ),
        migrations.AddField(
            model_name='batch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='batch',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='delete_reason',
            field=models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion'),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
