# Generated by Django 5.2.17 on 2026-09-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_alter_batch_options_alter_batchschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='kind',
            field=models.CharField(choices=[('regular', 'Regular'), ('internship', 'Internship'), ('modular', 'Modular')], db_index=True, default='regular', help_text='Regular, internship or modular. Descriptive today; see BatchKind.', max_length=12, verbose_name='kind'),
        ),
    ]
