# Generated by Django 5.2.17 on 2026-09-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_batch_kind'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The centre this class runs at. A course is shared; a class is not.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='organisation.branch', verbose_name='branch'),
        ),
    ]
