# Generated by Django 5.2.17 on 2026-08-31 22:00

import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_sessions', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], db_index=True, max_length=20, verbose_name='status')),
                ('note', models.CharField(blank=True, max_length=255, validators=[apps.common.validators.validate_no_control_characters], verbose_name='note')),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='marked at')),
                ('previous_status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], help_text='What it was before the last correction. Empty if never corrected.', max_length=20, verbose_name='previous status')),
                ('corrected_at', models.DateTimeField(blank=True, null=True, verbose_name='corrected at')),
                ('correction_reason', models.CharField(blank=True, max_length=255, verbose_name='correction reason')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrected', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='enrollments.enrollment')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='class_sessions.classsession')),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'ordering': ('-session__session_date', 'enrollment__student__student_id'),
                'indexes': [models.Index(fields=['enrollment', 'status'], name='attend_enrol_status_idx'), models.Index(fields=['session', 'status'], name='attend_session_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'enrollment'), name='attendance_one_per_session_enrollment')],
            },
        ),
    ]
