# Generated by Django 5.2.17 on 2026-09-15 23:02

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20, verbose_name='from status')),
                ('to_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20, verbose_name='to status')),
                ('reason', models.CharField(blank=True, max_length=255, validators=[apps.common.validators.validate_no_control_characters], verbose_name='reason')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections_made', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name': 'attendance correction',
                'verbose_name_plural': 'attendance corrections',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['record', '-created_at'], name='attend_correction_record_idx')],
            },
        ),
    ]
