# Generated by Django 5.2.17 on 2026-09-01 02:53

import apps.common.uploads
import apps.common.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_batch_code_sequence'),
        ('courses', '0002_course_code_sequence'),
        ('enrollments', '0001_initial'),
        ('trainers', '0002_trainer_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='code')),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('deliverables', models.TextField(blank=True, help_text='What the student must hand in.', verbose_name='deliverables')),
                ('kind', models.CharField(choices=[('small', 'Small project'), ('major', 'Major project'), ('capstone', 'Capstone project')], default='small', max_length=10, verbose_name='kind')),
                ('is_required', models.BooleanField(default=True, help_text='Required projects must be finished before a course can be completed.', verbose_name='required')),
                ('allow_team', models.BooleanField(default=False, editable=False, verbose_name='team project')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='starts')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='due')),
                ('requires_repository_url', models.BooleanField(default=False, verbose_name='repository URL required')),
                ('requires_deployment_url', models.BooleanField(default=False, verbose_name='deployment URL required')),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, verbose_name='maximum marks')),
                ('passing_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='passing marks')),
                ('rubric', models.JSONField(blank=True, default=list, verbose_name='rubric')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=12, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('batch', models.ForeignKey(blank=True, help_text='Leave empty to set this for every batch running the course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='batches.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='courses.module')),
                ('reviewer', models.ForeignKey(blank=True, help_text="Default mentor. A batch's own trainer may review regardless.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_mentored', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('rework', 'Rework requested'), ('approved', 'Approved'), ('completed', 'Completed')], default='assigned', max_length=14, verbose_name='status')),
                ('repository_url', models.URLField(blank=True, max_length=500, verbose_name='repository URL')),
                ('deployment_url', models.URLField(blank=True, max_length=500, verbose_name='deployment URL')),
                ('notes', models.TextField(blank=True, verbose_name='student notes')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('submission_count', models.PositiveSmallIntegerField(default=0, help_text='Rework sends a project back, so a student may submit more than once.', verbose_name='times submitted')),
                ('is_late', models.BooleanField(default=False, verbose_name='late')),
                ('rubric_scores', models.JSONField(blank=True, default=dict, verbose_name='rubric scores')),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='marks awarded')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='enrollments.enrollment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='projects.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_projects_reviewed', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'student project',
                'verbose_name_plural': 'student projects',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.common.uploads.submission_upload_to, verbose_name='file')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='extension')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='size in bytes')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('student_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.studentproject')),
            ],
            options={
                'verbose_name': 'project file',
                'verbose_name_plural': 'project files',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['course', 'status'], name='project_course_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['batch', 'status'], name='project_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['end_date'], name='project_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('max_marks__gt', 0)), name='project_max_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('passing_marks__isnull', True), ('passing_marks__lte', models.F('max_marks')), _connector='OR'), name='project_passing_within_max'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='project_dates_ordered'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['project', 'status'], name='studentproject_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['enrollment'], name='studentproject_enrolment_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentproject',
            constraint=models.UniqueConstraint(fields=('project', 'enrollment'), name='studentproject_one_per_student'),
        ),
        migrations.AddConstraint(
            model_name='studentproject',
            constraint=models.CheckConstraint(condition=models.Q(('marks_awarded__isnull', True), ('marks_awarded__gte', 0), _connector='OR'), name='studentproject_marks_not_negative'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['student_project'], name='projectfile_parent_idx'),
        ),
    ]
