# Generated by Django 5.2.17 on 2026-09-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_code_sequence'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectfile',
            name='projectfile_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentproject',
            name='studentproject_enrolment_idx',
        ),
    ]
