# Generated by Django 5.2.17 on 2026-08-31 22:14

import apps.common.uploads
import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_batch_code_sequence'),
        ('courses', '0002_course_code_sequence'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='code')),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('submission_kind', models.CharField(choices=[('file', 'File upload'), ('text', 'Written answer'), ('link', 'Link'), ('any', 'Any of the above')], default='file', max_length=10, verbose_name='submission kind')),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, verbose_name='maximum marks')),
                ('passing_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to take the passing rule from the academic configuration.', max_digits=6, null=True, verbose_name='passing marks')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='due at')),
                ('allow_late', models.BooleanField(default=True, help_text='Late work is accepted and flagged, rather than refused.', verbose_name='allow late submission')),
                ('late_cutoff_at', models.DateTimeField(blank=True, help_text='Nothing is accepted after this moment, late or not.', null=True, verbose_name='late cutoff')),
                ('allow_resubmission', models.BooleanField(default=False, verbose_name='allow resubmission')),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, verbose_name='maximum attempts')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=12, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('batch', models.ForeignKey(blank=True, help_text='Leave empty to set this work for every batch running the course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='batches.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursework', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='courses.lesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='courses.module')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('file', models.FileField(max_length=255, upload_to=apps.common.uploads.assignment_attachment_upload_to, verbose_name='file')),
                ('original_filename', models.CharField(blank=True, help_text='Display only — never used to build a path.', max_length=255, verbose_name='original filename')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='content type')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='size in bytes')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignments.assignment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assignment attachment',
                'verbose_name_plural': 'assignment attachments',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.PositiveSmallIntegerField(default=1, verbose_name='attempt')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned for rework')], default='submitted', max_length=12, verbose_name='status')),
                ('text_answer', models.TextField(blank=True, verbose_name='written answer')),
                ('link_url', models.URLField(blank=True, max_length=500, verbose_name='link')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='submitted at')),
                ('is_late', models.BooleanField(default=False, verbose_name='late')),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='marks awarded')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='graded at')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='enrollments.enrollment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_graded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assignment submission',
                'verbose_name_plural': 'assignment submissions',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.common.uploads.submission_upload_to, verbose_name='file')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='extension')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='size in bytes')),
                ('checksum', models.CharField(blank=True, help_text='Of the bytes as received, so integrity can be proven later.', max_length=64, verbose_name='SHA-256')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.assignmentsubmission')),
            ],
            options={
                'verbose_name': 'submission file',
                'verbose_name_plural': 'submission files',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', 'status'], name='assignment_course_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['batch', 'status'], name='assignment_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_at'], name='assignment_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('max_marks__gt', 0)), name='assignment_max_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('passing_marks__isnull', True), ('passing_marks__lte', models.F('max_marks')), _connector='OR'), name='assignment_passing_within_max'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='assignment_attempts_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('late_cutoff_at__isnull', True), models.Q(('due_at__isnull', False), ('late_cutoff_at__gte', models.F('due_at'))), _connector='OR'), name='assignment_late_cutoff_after_due'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='submission_assign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['enrollment', 'assignment'], name='submission_enrol_assign_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'enrollment', 'attempt'), name='submission_one_row_per_attempt'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('marks_awarded__isnull', True), ('marks_awarded__gte', 0), _connector='OR'), name='submission_marks_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('attempt__gte', 1)), name='submission_attempt_at_least_one'),
        ),
        migrations.AddIndex(
            model_name='submissionfile',
            index=models.Index(fields=['submission'], name='submission_file_parent_idx'),
        ),
    ]
