# Generated by Django 5.2.17 on 2026-09-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_code_sequence'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submissionfile',
            name='submission_file_parent_idx',
        ),
    ]
