# Generated by Django 5.2.17 on 2026-08-31 10:56

import apps.common.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer_id', models.CharField(editable=False, help_text='Human-readable identifier, e.g. GRS-T-00007. Allocated by the system.', max_length=20, unique=True, verbose_name='trainer ID')),
                ('professional_title', models.CharField(blank=True, help_text='For example: Senior Linux Trainer.', max_length=150, validators=[apps.common.validators.validate_no_control_characters], verbose_name='professional title')),
                ('bio', models.TextField(blank=True, max_length=2000, verbose_name='biography')),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Short tags, e.g. Python, RHCSA, Networking.', size=30, verbose_name='skills')),
                ('expertise', models.TextField(blank=True, help_text='Narrative description of specialisation.', max_length=1000, verbose_name='areas of expertise')),
                ('qualifications', models.TextField(blank=True, max_length=1000, verbose_name='qualifications and certifications')),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(70)], verbose_name='years of experience')),
                ('professional_links', models.JSONField(blank=True, default=dict, help_text='Optional map of linkedin / github / website to HTTPS URLs.', validators=[apps.common.validators.validate_professional_links], verbose_name='professional links')),
                ('is_accepting_assignments', models.BooleanField(db_index=True, default=True, help_text='Availability for future course and batch assignment. Separate from account status: a trainer can be active but unavailable.', verbose_name='accepting assignments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trainer profile',
                'verbose_name_plural': 'trainer profiles',
                'ordering': ('trainer_id',),
                'indexes': [models.Index(fields=['is_accepting_assignments', '-created_at'], name='trainer_avail_idx')],
            },
        ),
    ]
