# Generated by Django 5.2.17 on 2026-09-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('trainers', '0002_trainer_id_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The centre this trainer works at. It is what stops a class at one centre being staffed from another.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainers', to='organisation.branch', verbose_name='branch'),
        ),
    ]
