# Generated by Django 5.2.17 on 2026-09-17 06:58

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0009_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('key', models.CharField(help_text='Stable identifier a caller (the composer, an automation action) names.', max_length=60, verbose_name='key')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('in_app', 'In-app')], max_length=10, verbose_name='channel')),
                ('kind', models.CharField(max_length=60, verbose_name='kind')),
                ('language', models.CharField(default='en', max_length=8, verbose_name='language')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=10, verbose_name='status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message template',
                'verbose_name_plural': 'message templates',
                'ordering': ('key',),
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='version number')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML body')),
                ('body_text', models.TextField(blank=True, verbose_name='text body')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='variables')),
                ('provider_template_id', models.CharField(blank=True, max_length=120, verbose_name='provider template id')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='communication.messagetemplate')),
            ],
            options={
                'verbose_name': 'template version',
                'verbose_name_plural': 'template versions',
                'ordering': ('template', '-number'),
            },
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='The currently published version. Null until the first publish.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communication.templateversion'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('in_app', 'In-app')], max_length=10, verbose_name='channel')),
                ('address', models.CharField(blank=True, max_length=254, verbose_name='address')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='variables')),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=10, verbose_name='state')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='next attempt')),
                ('provider_message_id', models.CharField(blank=True, max_length=120, verbose_name='provider message id')),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='error')),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('email_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.emailmessage')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_deliveries', to=settings.AUTH_USER_MODEL)),
                ('related_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='communication.templateversion')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
            },
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='templateversion_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('key',), name='messagetemplate_key_unique'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['state', 'next_attempt_at'], name='delivery_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['recipient', '-created_at'], name='delivery_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['related_type', 'related_id'], name='delivery_related_idx'),
        ),
    ]
