# Generated by Django 5.2.17 on 2026-09-17 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_seed_templates'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0009_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(condition=models.Q(('state__in', ['queued', 'failed'])), fields=['next_attempt_at'], name='delivery_retry_due_idx'),
        ),
    ]
