# Generated by Django 5.2.17 on 2026-09-01 09:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('course.updated', 'Course updated'), ('batch.updated', 'Batch updated'), ('announcement', 'Announcement'), ('assignment.due', 'Assignment deadline'), ('assignment.graded', 'Assignment graded'), ('test.scheduled', 'Weekly test scheduled'), ('result.published', 'Result published'), ('exam.reminder', 'Examination reminder'), ('project.reviewed', 'Project reviewed'), ('attendance.warning', 'Attendance warning'), ('completion.approved', 'Course completion approved'), ('certificate.issued', 'Certificate issued')], max_length=32, verbose_name='kind')),
                ('category', models.CharField(choices=[('academic', 'Coursework and results'), ('schedule', 'Classes, tests and deadlines'), ('announcements', 'Announcements'), ('administrative', 'Completion and certificates')], max_length=16, verbose_name='category')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('link_path', models.CharField(blank=True, max_length=300, verbose_name='link')),
                ('resource_type', models.CharField(blank=True, max_length=40, verbose_name='resource type')),
                ('resource_id', models.CharField(blank=True, max_length=64, verbose_name='resource id')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_email', models.EmailField(max_length=254, verbose_name='to')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('template', models.CharField(blank=True, max_length=60, verbose_name='template')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('abandoned', 'Given up')], default='pending', max_length=10, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='last error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='next attempt')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'email message',
                'verbose_name_plural': 'email messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_academic', models.BooleanField(default=True, verbose_name='coursework and results')),
                ('email_schedule', models.BooleanField(default=True, verbose_name='classes, tests and deadlines')),
                ('email_announcements', models.BooleanField(default=True, verbose_name='announcements')),
                ('email_administrative', models.BooleanField(default=True, verbose_name='completion and certificates')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notification_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at'], name='notification_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'next_attempt_at'], name='email_pending_idx'),
        ),
    ]
