# Generated by Django 5.2.17 on 2026-09-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('course.updated', 'Course updated'), ('batch.updated', 'Batch updated'), ('announcement', 'Announcement'), ('assignment.due', 'Assignment deadline'), ('assignment.graded', 'Assignment graded'), ('test.scheduled', 'Weekly test scheduled'), ('result.published', 'Result published'), ('exam.reminder', 'Examination reminder'), ('project.reviewed', 'Project reviewed'), ('attendance.warning', 'Attendance warning'), ('warning.digest', 'Weekly warnings digest'), ('completion.approved', 'Course completion approved'), ('certificate.issued', 'Certificate issued')], max_length=32, verbose_name='kind'),
        ),
    ]
