# Generated by Django 5.2.17 on 2026-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_requirement_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('academic', 'Coursework and results'), ('schedule', 'Classes, tests and deadlines'), ('announcements', 'Announcements'), ('administrative', 'Completion and certificates'), ('security', 'Security')], max_length=16, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('course.updated', 'Course updated'), ('batch.updated', 'Batch updated'), ('announcement', 'Announcement'), ('requirement.raised', 'Trainer requirement raised'), ('requirement.replied', 'Reply on a trainer requirement'), ('assignment.due', 'Assignment deadline'), ('assignment.graded', 'Assignment graded'), ('test.scheduled', 'Weekly test scheduled'), ('result.published', 'Result published'), ('exam.reminder', 'Examination reminder'), ('project.reviewed', 'Project reviewed'), ('attendance.warning', 'Attendance warning'), ('warning.digest', 'Weekly warnings digest'), ('export.ready', 'Export ready'), ('export.failed', 'Export failed'), ('completion.approved', 'Course completion approved'), ('certificate.issued', 'Certificate issued'), ('mfa.enrolled', 'Two-factor authentication turned on'), ('mfa.disabled', 'Two-factor authentication turned off')], max_length=32, verbose_name='kind'),
        ),
    ]
