# Generated by Django 5.2.17 on 2026-09-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('course.updated', 'Course updated'), ('batch.updated', 'Batch updated'), ('announcement', 'Announcement'), ('requirement.raised', 'Trainer requirement raised'), ('requirement.replied', 'Reply on a trainer requirement'), ('assignment.due', 'Assignment deadline'), ('assignment.graded', 'Assignment graded'), ('test.scheduled', 'Weekly test scheduled'), ('result.published', 'Result published'), ('exam.reminder', 'Examination reminder'), ('project.reviewed', 'Project reviewed'), ('attendance.warning', 'Attendance warning'), ('warning.digest', 'Weekly warnings digest'), ('export.ready', 'Export ready'), ('export.failed', 'Export failed'), ('completion.approved', 'Course completion approved'), ('certificate.issued', 'Certificate issued'), ('mfa.enrolled', 'Two-factor authentication turned on'), ('mfa.disabled', 'Two-factor authentication turned off'), ('session.new_device', 'Sign-in from a new device'), ('session.revoked_by_admin', 'A session was ended by an administrator'), ('activity.assigned', 'Activity assigned to you'), ('activity.completed', 'Activity completed'), ('activity.reminder', 'Activity due soon'), ('risk.level_changed', 'Student risk level changed'), ('activity.overdue', 'Activity overdue'), ('project.overdue', 'Project overdue')], max_length=32, verbose_name='kind'),
        ),
    ]
