# Generated by Django 5.2.17 on 2026-09-06 18:08

import apps.common.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0004_alter_batch_options_alter_batchschedule_options_and_more'),
        ('class_sessions', '0002_classsession_actual_lesson_and_more'),
        ('courses', '0002_course_code_sequence'),
        ('trainers', '0002_trainer_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('report_date', models.DateField(db_index=True, verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('planned_topic', models.CharField(blank=True, max_length=250, validators=[apps.common.validators.validate_no_control_characters], verbose_name='planned topic')),
                ('actual_topic', models.CharField(blank=True, max_length=250, validators=[apps.common.validators.validate_no_control_characters], verbose_name='actual topic')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='students on roster')),
                ('present_count', models.PositiveIntegerField(default=0, verbose_name='present')),
                ('absent_count', models.PositiveIntegerField(default=0, verbose_name='absent')),
                ('online_count', models.PositiveIntegerField(default=0, verbose_name='joined online')),
                ('offline_count', models.PositiveIntegerField(default=0, verbose_name='joined in person')),
                ('teaching_notes', models.TextField(blank=True, max_length=2000, verbose_name='teaching notes')),
                ('issues', models.TextField(blank=True, max_length=2000, verbose_name='issues')),
                ('student_concerns', models.TextField(blank=True, max_length=2000, verbose_name='student concerns')),
                ('assignment_given', models.BooleanField(default=False, verbose_name='assignment given')),
                ('assessment_conducted', models.BooleanField(default=False, verbose_name='assessment conducted')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision required')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('manager_comments', models.TextField(blank=True, max_length=2000, verbose_name='manager comments')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsr_reports', to='batches.batch')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_reports', to='courses.module')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(help_text='The class this report is about. One report per class.', on_delete=django.db.models.deletion.CASCADE, related_name='dsr', to='class_sessions.classsession')),
                ('trainer', models.ForeignKey(help_text='Who wrote this report.', on_delete=django.db.models.deletion.PROTECT, related_name='dsr_reports', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'daily status report',
                'verbose_name_plural': 'daily status reports',
                'ordering': ('-report_date', '-created_at'),
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['batch', '-report_date'], name='dsr_batch_date_idx'), models.Index(fields=['trainer', '-report_date'], name='dsr_trainer_date_idx'), models.Index(fields=['status', '-report_date'], name='dsr_status_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='dsr_end_after_start')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
