# Generated by Django 5.2.17 on 2026-10-03 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_soft_delete'),
        ('courses', '0005_partial_uniqueness'),
        ('dsr', '0001_initial'),
        ('enrollments', '0004_enrollment_is_upgrade_enrollment_transferred_to_and_more'),
        ('forms', '0006_alter_formdefinition_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsr',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='due at'),
        ),
        migrations.AddField(
            model_name='dsr',
            name='extra_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='extra answers'),
        ),
        migrations.AddField(
            model_name='dsr',
            name='form_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dsr_reports', to='forms.formversion'),
        ),
        migrations.AddField(
            model_name='dsr',
            name='homework',
            field=models.TextField(blank=True, max_length=2000, verbose_name='homework'),
        ),
        migrations.AddField(
            model_name='dsr',
            name='homework_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_reports', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='dsr',
            name='homework_due_on',
            field=models.DateField(blank=True, null=True, verbose_name='homework due'),
        ),
        migrations.AddField(
            model_name='dsr',
            name='lessons_covered',
            field=models.ManyToManyField(blank=True, related_name='dsr_reports', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='dsr',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='overdue notice sent at'),
        ),
        migrations.AddField(
            model_name='dsr',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reminder sent at'),
        ),
        migrations.AddField(
            model_name='dsr',
            name='topic_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='topic status'),
        ),
        migrations.CreateModel(
            name='DSRAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='caption')),
                ('dsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dsr.dsr')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dsr_attachments', to='forms.formupload')),
            ],
            options={
                'verbose_name': 'class report attachment',
                'verbose_name_plural': 'class report attachments',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DSRStudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.CharField(choices=[('doubt', 'Had a doubt'), ('needs_attention', 'Needs attention'), ('did_well', 'Did well'), ('absent_reason', 'Reason for absence'), ('other', 'Other')], max_length=20, verbose_name='flag')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='note')),
                ('dsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='dsr.dsr')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsr_notes', to='enrollments.enrollment')),
            ],
            options={
                'verbose_name': 'class report student note',
                'verbose_name_plural': 'class report student notes',
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('dsr', 'enrollment', 'flag'), name='dsr_student_note_unique')],
            },
        ),
    ]
