# Generated by Django 5.2.17 on 2026-08-31 21:54

import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_batch_code_sequence'),
        ('trainers', '0002_trainer_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField(db_index=True, verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('timezone_name', models.CharField(default='Asia/Kolkata', max_length=64, verbose_name='time zone')),
                ('topic', models.CharField(blank=True, help_text='What was covered. Filled in by the trainer.', max_length=250, validators=[apps.common.validators.validate_no_control_characters], verbose_name='topic')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='notes')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='location')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], db_index=True, default='scheduled', max_length=20, verbose_name='status')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('attendance_taken_at', models.DateTimeField(blank=True, null=True, verbose_name='attendance taken at')),
                ('attendance_taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_registers_taken', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='batches.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL)),
                ('rescheduled_to', models.OneToOneField(blank=True, help_text='The replacement class, when this one was moved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_from', to='class_sessions.classsession')),
                ('schedule', models.ForeignKey(blank=True, help_text='The weekly slot this was generated from. Cleared if the slot is deleted — the session itself is history and stays.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='batches.batchschedule')),
                ('trainer', models.ForeignKey(blank=True, help_text='Who actually took this class. Frozen at generation time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'class session',
                'verbose_name_plural': 'class sessions',
                'ordering': ('-session_date', 'start_time'),
                'indexes': [models.Index(fields=['batch', '-session_date'], name='session_batch_date_idx'), models.Index(fields=['trainer', '-session_date'], name='session_trainer_date_idx'), models.Index(fields=['status', 'session_date'], name='session_status_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='session_end_after_start'), models.UniqueConstraint(fields=('batch', 'session_date', 'start_time'), name='session_unique_per_batch_slot')],
            },
        ),
        migrations.CreateModel(
            name='TrainerAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='assigned at')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Set when the next trainer takes over.', null=True, verbose_name='ended at')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_history', to='batches.batch')),
                ('trainer', models.ForeignKey(blank=True, help_text='Null records the batch being left without a trainer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_history', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'trainer assignment',
                'verbose_name_plural': 'trainer assignment history',
                'ordering': ('-assigned_at',),
                'indexes': [models.Index(fields=['batch', '-assigned_at'], name='trainerhist_batch_idx'), models.Index(fields=['trainer', '-assigned_at'], name='trainerhist_trainer_idx')],
            },
        ),
    ]
