# Generated by Django 5.2.17 on 2026-09-06 18:01

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_alter_batch_options_alter_batchschedule_options_and_more'),
        ('class_sessions', '0001_initial'),
        ('courses', '0002_course_code_sequence'),
        ('trainers', '0002_trainer_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='actual_lesson',
            field=models.ForeignKey(blank=True, help_text='What the class actually covered, confirmed by whoever took it. May differ from `planned_lesson` — a trainer who ran behind or jumped ahead is exactly the case this field exists to record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_sessions', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='planned_lesson',
            field=models.ForeignKey(blank=True, help_text="What the curriculum says this class should cover. Set ahead of time, by hand or by autoplan, so a batch's progress can be judged against a plan rather than only against the calendar.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_sessions', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='topic_status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('rescheduled', 'Rescheduled')], db_index=True, default='planned', max_length=20, verbose_name='topic status'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='topic',
            field=models.CharField(blank=True, help_text='What was covered. Filled in by the trainer, in their own words.', max_length=250, validators=[apps.common.validators.validate_no_control_characters], verbose_name='topic'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['batch', 'topic_status'], name='session_batch_topic_idx'),
        ),
    ]
