# Generated by Django 5.2.17 on 2026-09-01 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0002_enrollment_delivery_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('eligible', 'Eligible, awaiting approval'), ('approved', 'Approved'), ('rejected', 'Not approved')], default='in_progress', max_length=12, verbose_name='status')),
                ('became_eligible_at', models.DateTimeField(blank=True, null=True, verbose_name='became eligible at')),
                ('rule_snapshot', models.JSONField(blank=True, default=dict, verbose_name='rules at decision')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('decision_note', models.CharField(blank=True, max_length=500, verbose_name='note')),
                ('completed_on', models.DateField(blank=True, help_text='The date the course is recorded as finished. Appears on the certificate.', null=True, verbose_name='completion date')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions_decided', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='enrollments.enrollment')),
            ],
            options={
                'verbose_name': 'course completion',
                'verbose_name_plural': 'course completions',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['status'], name='completion_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('completed_on__isnull', False), _connector='OR'), name='completion_approved_has_a_date')],
            },
        ),
    ]
