# Generated by Django 5.2.17 on 2026-08-31 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_batch_code_sequence'),
        ('courses', '0002_course_code_sequence'),
        ('students', '0002_student_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Human-readable identifier, e.g. GRS-E-00307.', max_length=20, unique=True, verbose_name='enrolment code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='enrolled at')),
                ('start_date', models.DateField(blank=True, help_text='Defaults to the batch start date.', null=True, verbose_name='access start date')),
                ('access_end_date', models.DateField(blank=True, help_text='Optional. After this date the enrolment no longer opens the course.', null=True, verbose_name='access end date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='status last changed at')),
                ('status_note', models.CharField(blank=True, help_text='Why the status last changed. Shown to administrators only.', max_length=255, verbose_name='status note')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='batches.batch')),
                ('course', models.ForeignKey(help_text="Always the batch's course. Stored so access queries need one join fewer.", on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Protected: educational history is never removed with the profile.', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'enrolment',
                'verbose_name_plural': 'enrolments',
                'ordering': ('-enrolled_at',),
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=20, verbose_name='status')),
                ('first_accessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='first opened at')),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last opened at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'lesson progress',
                'verbose_name_plural': 'lesson progress',
                'ordering': ('-last_accessed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course', 'status'], name='enrol_student_course_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['batch', 'status'], name='enrol_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='enrol_course_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active', 'suspended'])), fields=('student', 'batch'), name='enrollment_one_live_per_student_batch'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'status'], name='progress_enrol_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', '-last_accessed_at'], name='progress_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='progress_one_per_enrollment_lesson'),
        ),
    ]
