# Generated by Django 5.2.17 on 2026-09-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('offline', 'In the classroom'), ('online', 'Online'), ('hybrid', 'Both')], default='', help_text='Leave empty to follow the batch.', max_length=10, verbose_name='delivery mode'),
        ),
    ]
