# Generated by Django 5.2.17 on 2026-09-06 17:45

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_alter_batch_options_alter_batchschedule_options_and_more'),
        ('courses', '0002_course_code_sequence'),
        ('enrollments', '0002_enrollment_delivery_mode'),
        ('students', '0002_student_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'base_manager_name': 'all_objects', 'ordering': ('-enrolled_at',), 'verbose_name': 'enrolment', 'verbose_name_plural': 'enrolments'},
        ),
        migrations.AlterModelManagers(
            name='enrollment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='enrollment_one_live_per_student_batch',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='delete_reason',
            field=models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['pending', 'active', 'suspended'])), fields=('student', 'batch'), name='enrollment_one_live_per_student_batch'),
        ),
    ]
