# Generated by Django 5.2.17 on 2026-09-06 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_alter_enrollment_options_alter_enrollment_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_upgrade',
            field=models.BooleanField(default=False, help_text='A move to a different or longer programme, rather than a lateral transfer.', verbose_name='was an upgrade'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transferred_to',
            field=models.OneToOneField(blank=True, help_text='Where this student went. Set when the enrolment was moved, not cancelled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='enrollments.enrollment'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred to another batch')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
    ]
