# Generated by Django 5.2.17 on 2026-09-01 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_code_sequence'),
        ('enrollments', '0002_enrollment_delivery_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, help_text='Why it was worth coming back to.', max_length=200, verbose_name='note')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'lesson bookmark',
                'verbose_name_plural': 'lesson bookmarks',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['enrollment', '-created_at'], name='bookmark_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'lesson'), name='bookmark_one_per_lesson')],
            },
        ),
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='note')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'lesson note',
                'verbose_name_plural': 'lesson notes',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['enrollment', '-updated_at'], name='note_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'lesson'), name='note_one_per_lesson')],
            },
        ),
    ]
