# Generated by Django 5.2.17 on 2026-08-31 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(blank=True, help_text='Actor identity captured at write time; survives account deletion.', max_length=254)),
                ('action', models.CharField(choices=[('auth.login.succeeded', 'Login succeeded'), ('auth.login.failed', 'Login failed'), ('auth.logout', 'Logout'), ('user.created', 'User created'), ('user.updated', 'User updated'), ('user.deactivated', 'User deactivated'), ('user.listed', 'User list viewed'), ('authz.denied', 'Permission denied')], db_index=True, max_length=64)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied')], default='success', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Extra non-sensitive detail. Scrubbed of secrets on write.')),
                ('actor', models.ForeignKey(blank=True, help_text='Null for anonymous or system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_resource_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_time_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_time_idx')],
            },
        ),
    ]
