# Generated by Django 5.2.17 on 2026-08-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('auth.login.succeeded', 'Login succeeded'), ('auth.login.failed', 'Login failed'), ('auth.logout', 'Logout'), ('auth.sessions.revoked', 'Sessions revoked'), ('auth.password.changed', 'Password changed'), ('auth.password.reset_requested', 'Password reset requested'), ('auth.password.reset_completed', 'Password reset completed'), ('auth.password.reset_failed', 'Password reset failed'), ('auth.email.verification_requested', 'Email verification requested'), ('auth.email.verified', 'Email verified'), ('auth.email.verification_failed', 'Email verification failed'), ('user.created', 'User created'), ('user.updated', 'User updated'), ('user.activated', 'User activated'), ('user.deactivated', 'User deactivated'), ('user.role_changed', 'User role changed'), ('user.listed', 'User list viewed'), ('user.profile_image.updated', 'Profile image updated'), ('user.profile_image.removed', 'Profile image removed'), ('student.created', 'Student created'), ('student.updated', 'Student profile updated'), ('student.fee_status.changed', 'Student fee status changed'), ('trainer.created', 'Trainer created'), ('trainer.updated', 'Trainer profile updated'), ('authz.denied', 'Permission denied')], db_index=True, max_length=64),
        ),
    ]
