# Generated by Django 5.2.17 on 2026-09-16 01:53

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0007_alter_batch_branch'),
        ('enrollments', '0004_enrollment_is_upgrade_enrollment_transferred_to_and_more'),
        ('forms', '0002_seed_catalog'),
        ('organisation', '0002_default_branch'),
        ('students', '0008_alter_studentprofile_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('reopened', 'Reopened'), ('under_review', 'Under review'), ('approved', 'Approved'), ('requires_action', 'Requires action')], default='draft', max_length=16, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='priority')),
                ('planned_at', models.DateTimeField(blank=True, null=True, verbose_name='planned at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='due at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='reminder sent at')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (minutes)')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('mixed', 'Mixed'), ('n/a', 'Not applicable')], default='n/a', max_length=20, verbose_name='result')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='max score')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('review_note', models.TextField(blank=True, verbose_name='review note')),
                ('student_visible', models.BooleanField(default=True, verbose_name='visible to student')),
                ('client_key', models.CharField(blank=True, default='', max_length=100, verbose_name='client key')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='batches.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='organisation.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='enrollments.enrollment')),
                ('form_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forms.formresponse')),
                ('form_version', models.ForeignKey(blank=True, help_text='Pinned at creation. Never changes after.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='forms.formversion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='work.activity')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ('-created_at',),
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('reopened', 'Reopened'), ('under_review', 'Under review'), ('approved', 'Approved'), ('requires_action', 'Requires action')], max_length=16, verbose_name='from')),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('reopened', 'Reopened'), ('under_review', 'Under review'), ('approved', 'Approved'), ('requires_action', 'Requires action')], max_length=16, verbose_name='to')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changes')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='work.activity')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activity history entry',
                'verbose_name_plural': 'activity history',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('slug', models.CharField(max_length=60, verbose_name='slug')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('interview', 'Interview'), ('mentoring', 'Mentoring'), ('counselling', 'Counselling'), ('review', 'Review'), ('placement', 'Placement'), ('feedback', 'Feedback'), ('warning', 'Warning'), ('follow_up', 'Follow-up'), ('other', 'Other')], max_length=30, verbose_name='category')),
                ('allowed_creator_roles', models.JSONField(blank=True, default=list, verbose_name='allowed creator roles')),
                ('allowed_assignee_roles', models.JSONField(blank=True, default=list, verbose_name='allowed assignee roles')),
                ('visible_to_student', models.BooleanField(default=False, verbose_name='visible to student')),
                ('default_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='default duration (minutes)')),
                ('requires_review', models.BooleanField(default=False, verbose_name='requires review')),
                ('performance_weight', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='performance weight')),
                ('risk_effect', models.CharField(choices=[('none', 'No effect'), ('score_below_threshold', 'Low score raises risk')], default='none', max_length=30, verbose_name='risk effect')),
                ('reminder_minutes_before', models.PositiveIntegerField(blank=True, null=True, verbose_name='remind before (minutes)')),
                ('next_action', models.JSONField(blank=True, null=True, verbose_name='next action')),
                ('is_system', models.BooleanField(default=False, verbose_name='seeded by the catalog')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10, verbose_name='status')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_types', to='forms.formdefinition')),
            ],
            options={
                'verbose_name': 'activity type',
                'verbose_name_plural': 'activity types',
                'ordering': ('name',),
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='work.activitytype'),
        ),
        migrations.AddConstraint(
            model_name='activitytype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='activity_type_slug_unique'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['student', '-created_at'], name='activity_student_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['assigned_to', 'status', 'due_at'], name='activity_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['branch', 'status'], name='activity_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_by', 'client_key'], name='activity_client_key_idx'),
        ),
    ]
