# Generated by Django 5.2.17 on 2026-09-16 11:09

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_seed_catalog'),
        ('work', '0002_seed_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='performance_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='performance weight'),
        ),
        migrations.AddConstraint(
            model_name='activitytype',
            constraint=models.CheckConstraint(condition=models.Q(('performance_weight__gte', 0)), name='activity_type_performance_weight_non_negative'),
        ),
    ]
