# Generated by Django 5.2.17 on 2026-09-16 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('work', '0003_alter_activitytype_performance_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='automation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to='automation.automationrun'),
        ),
    ]
