# Generated by Django 5.2.17 on 2026-09-17 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_automationrule_is_system'),
        ('batches', '0007_alter_batch_branch'),
        ('enrollments', '0004_enrollment_is_upgrade_enrollment_transferred_to_and_more'),
        ('forms', '0002_seed_catalog'),
        ('organisation', '0002_default_branch'),
        ('students', '0008_alter_studentprofile_branch'),
        ('work', '0004_activity_automation_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(condition=models.Q(('status__in', ['planned', 'assigned', 'in_progress'])), fields=['due_at'], name='activity_open_due_idx'),
        ),
    ]
