# Generated by Django 5.2.17 on 2026-10-03 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0004_form_and_enquiry_triggers"),
        ("batches", "0007_alter_batch_branch"),
        ("enquiries", "0001_initial"),
        ("enrollments", "0004_enrollment_is_upgrade_enrollment_transferred_to_and_more"),
        ("forms", "0005_formassignment_enquiry"),
        ("organisation", "0002_default_branch"),
        ("students", "0008_alter_studentprofile_branch"),
        ("work", "0005_activity_activity_open_due_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="enquiries.enquiry",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="form_prefill",
            field=models.JSONField(blank=True, default=dict, verbose_name="form prefill"),
        ),
        migrations.AddField(
            model_name="activitytype",
            name="subject",
            field=models.CharField(
                choices=[("student", "Student"), ("enquiry", "Enquiry")],
                default="student",
                max_length=10,
                verbose_name="subject",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="students.studentprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["enquiry", "-created_at"], name="activity_enquiry_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("enquiry__isnull", True), ("student__isnull", False)),
                    models.Q(("enquiry__isnull", False), ("student__isnull", True)),
                    _connector="OR",
                ),
                name="activity_has_one_subject",
            ),
        ),
    ]
