# Generated by Django 5.2.17 on 2026-09-15 09:21

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='code')),
                ('resource', models.CharField(max_length=30, verbose_name='resource')),
                ('action', models.CharField(max_length=30, verbose_name='action')),
                ('category', models.CharField(choices=[('people', 'People'), ('academic', 'Academic'), ('operations', 'Operations'), ('configuration', 'Configuration'), ('communication', 'Communication'), ('system', 'System')], max_length=20, verbose_name='category')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('is_system', models.BooleanField(default=True, editable=False, verbose_name='system')),
                ('is_lockable', models.BooleanField(default=False, verbose_name='lockable')),
                ('is_active', models.BooleanField(default=True, help_text='False once the enum member is gone; rows are never deleted.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ('category', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('slug', models.SlugField(max_length=60, verbose_name='slug')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
                ('kind', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Administrator'), ('manager', 'Manager'), ('counsellor', 'Counsellor'), ('trainer', 'Trainer'), ('student', 'Student')], help_text='The system role this is built from. Fixes its place on the ladder and how far it sees; a custom role adjusts the set, never the kind.', max_length=20, verbose_name='kind')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10, verbose_name='status')),
                ('is_system', models.BooleanField(default=False, editable=False, verbose_name='system')),
                ('is_locked', models.BooleanField(default=False, help_text='Only a superadmin with a step-up may edit a locked role.', verbose_name='locked')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ('-is_system', 'kind', 'name'),
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(blank=True, choices=[('all', 'Every centre'), ('branch', 'Own centre'), ('assigned', 'Assigned batches and courses'), ('own', 'Own records')], default='', help_text="Empty means the role kind's floor.", max_length=10, verbose_name='scope')),
                ('is_locked', models.BooleanField(default=False, verbose_name='locked')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='authorization.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='authorization.role')),
            ],
            options={
                'verbose_name': 'role permission',
                'verbose_name_plural': 'role permissions',
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='role_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='role_permission_unique'),
        ),
    ]
