# Generated by Django 5.2.17 on 2026-09-15 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_seed_catalog'),
        ('batches', '0007_alter_batch_branch'),
        ('courses', '0005_partial_uniqueness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_grants', to='batches.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_grants', to='courses.course')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scope grant',
                'verbose_name_plural': 'scope grants',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('batch__isnull', False), ('course__isnull', True)), models.Q(('batch__isnull', True), ('course__isnull', False)), _connector='OR'), name='scope_grant_one_target'), models.UniqueConstraint(fields=('user', 'batch'), name='scope_grant_batch_unique'), models.UniqueConstraint(fields=('user', 'course'), name='scope_grant_course_unique')],
            },
        ),
    ]
