# Generated by Django 5.2.17 on 2026-09-14 11:47

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0007_alter_batch_branch'),
        ('organisation', '0002_default_branch'),
        ('trainers', '0004_alter_trainerprofile_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('details', models.TextField(blank=True, verbose_name='details')),
                ('needed_by', models.DateField(blank=True, null=True, verbose_name='needed by')),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=12, verbose_name='status')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('closing_note', models.CharField(blank=True, max_length=300, verbose_name='closing note')),
                ('batch', models.ForeignKey(blank=True, help_text='The batch this is about, if there is one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_requirements', to='batches.batch', verbose_name='batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_requirements', to='organisation.branch', verbose_name='centre')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='closed by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_fulfilled', to='trainers.trainerprofile', verbose_name='fulfilled by')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements_raised', to=settings.AUTH_USER_MODEL, verbose_name='raised by')),
            ],
            options={
                'verbose_name': 'trainer requirement',
                'verbose_name_plural': 'trainer requirements',
                'ordering': ('-created_at',),
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RequirementReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(verbose_name='message')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='requirements.trainerrequirement')),
            ],
            options={
                'verbose_name': 'requirement reply',
                'verbose_name_plural': 'requirement replies',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='trainerrequirement',
            index=models.Index(fields=['branch', 'status', '-created_at'], name='requirement_branch_idx'),
        ),
    ]
