"""Multi-factor authentication (ERP Phase 5, ADR-05): TOTP, recovery codes,
and the pending-MFA sign-in state.

Builds directly on Phase 4's :mod:`apps.accounts.otp` rather than duplicating
it: email is still one of the three factors here, and it is still
``OneTimeCode`` underneath — this module passes ``purpose="login"`` (reserved
for exactly this by Phase 4) or ``purpose="step_up"`` and otherwise leaves
that model alone. Sits beside :mod:`apps.accounts.otp` and
:mod:`apps.accounts.stepup`, not inside ``services.py``, for the same reason
those two do (see their module docstrings): the views call these functions
directly, so a serializer or a view is never where the decision "is this code
right" gets made.

Two more mechanisms this module owns:

* **TOTP** (RFC 6238, 30-second step, ±1 step tolerance). The shared secret
  is generated by :mod:`pyotp`, encrypted at rest with ``Fernet`` under
  ``settings.MFA_ENCRYPTION_KEY`` (environment-only, no production default —
  see ``config/settings/hardened.py``), and never appears in a log line, an
  audit row or an API response after the one enrolment call that hands it to
  the user. Replay of an already-accepted step (or anything before it) is
  refused by remembering ``MfaDevice.last_used_step``.
* **Recovery codes.** Ten single-use codes, hashed the same way
  ``OneTimeCode`` hashes its codes (SHA-256, no per-row salt needed — these
  are high-entropy random strings, not 6-digit codes, so there is nothing a
  rainbow table gains from a shared hash function). Issuing a fresh batch
  invalidates every code that came before it, including ones already used —
  ``RecoveryCode`` rows for the old batch are deleted outright rather than
  soft-deleted, on purpose (see the model docstring): a "restorable" MFA
  bypass would be a real vulnerability, not a convenience.

The pending-MFA sign-in state
------------------------------
ADR-05's login flow: a correct password does not call ``django.contrib.auth.
login`` when MFA applies. Instead the *session* — still anonymous, since
``login()`` was never called — gets one key, ``mfa_pending``, holding only a
user id and an expiry five minutes out. Every ordinary endpoint already
refuses that session: ``IsActiveUser`` checks ``request.user.is_authenticated``,
which is ``False`` until ``POST /auth/mfa/verify/`` succeeds and calls
``login()`` for real. Nothing had to be taught to recognise "pending" as a
special kind of forbidden — it already looks exactly like "not signed in",
because that is what it is.
"""

from __future__ import annotations

import re
import secrets
from datetime import timedelta
from hashlib import sha256
from io import BytesIO
from typing import Any

import pyotp
from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.core.exceptions import ValidationError as DjangoValidationError
from django.db import models, transaction
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.audit.services import AuditAction, AuditResult, record
from apps.common.exceptions import ApplicationError, ConflictError
from apps.common.models import BaseModel

#: RFC 6238 defaults. Not policy-driven: changing the step size would desync
#: every already-enrolled authenticator app, which is not a knob an
#: administrator should be able to turn from a settings screen.
TOTP_STEP_SECONDS = 30
TOTP_DIGITS = 6
TOTP_VALID_WINDOW = 1  # ± one step either side of "now"
TOTP_ISSUER = "Grras LMS"

#: Fixed by ADR-05 ("Pending state expires in 5 min"), not a policy: this is
#: a property of the login flow itself, not an institution's risk appetite.
PENDING_SESSION_KEY = "mfa_pending"
PENDING_TTL_SECONDS = 5 * 60

RECOVERY_CODE_COUNT = 10


class MfaMethod(models.TextChoices):
    """The three ways a pending sign-in or a step-up may be proved."""

    TOTP = "totp", _("Authenticator app")
    EMAIL = "email", _("Email code")
    RECOVERY = "recovery", _("Recovery code")


class MfaEnrolmentConflict(ConflictError):
    default_detail = "MFA is already enabled. Disable it before enrolling a new device."
    default_code = "mfa_already_enrolled"


class MfaNoPendingEnrolment(ApplicationError):
    default_detail = "Start enrolment before confirming a code."
    default_code = "mfa_no_pending_enrolment"


class MfaNotEnabled(ApplicationError):
    default_detail = "MFA is not enabled on this account."
    default_code = "mfa_not_enabled"


class InvalidMfaCode(ApplicationError):
    """The one failure shape every method answers with.

    Deliberately generic (SECURITY_DECISIONS: never reveal, via message or
    timing, which mechanism specifically failed): a wrong TOTP code, an
    expired email code, an already-used recovery code and "no device at all"
    all reach the API caller as this same 400.
    """

    default_detail = "That code is not right or has expired."
    default_code = "invalid_code"


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class MfaDevice(BaseModel):
    """A user's TOTP device. One per user (``OneToOneField``).

    Not soft-deletable, and disable/re-enrol genuinely delete/overwrite the
    row rather than flag it — see the module docstring on why a "restorable"
    MFA artifact would be a vulnerability, not a convenience (same precedent
    as ``OneTimeCode``, which is also plain ``BaseModel``).

    An unconfirmed device (``confirmed_at`` is ``None``) is inert: it never
    counts toward "this user has MFA", is never offered as a login method,
    and is silently replaced by the next call to :func:`start_enrolment` —
    exactly the shape of "I scanned the QR code but never entered a code",
    which should cost the user nothing to retry.
    """

    user = models.OneToOneField(
        "accounts.User", on_delete=models.CASCADE, related_name="mfa_device"
    )
    secret_encrypted = models.BinaryField()
    confirmed_at = models.DateTimeField(null=True, blank=True)
    #: Replay guard (SECURITY_DECISIONS "MFA"). The last TOTP step accepted;
    #: anything at or before it is refused, confirmed or not.
    last_used_step = models.BigIntegerField(null=True, blank=True)
    name = models.CharField(max_length=60, default="Authenticator app")

    class Meta:
        verbose_name = _("MFA device")
        verbose_name_plural = _("MFA devices")

    def __str__(self) -> str:
        # Never the secret, encrypted or otherwise.
        state = "confirmed" if self.confirmed_at else "pending"
        return f"TOTP device for {self.user_id} ({state})"

    @property
    def is_confirmed(self) -> bool:
        return self.confirmed_at is not None


class RecoveryCode(BaseModel):
    """One single-use recovery code. Ten are issued together and share a
    "generation" only in the sense that :func:`issue_recovery_codes` deletes
    every prior row for the user before creating the new ten."""

    user = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, related_name="recovery_codes"
    )
    code_hash = models.CharField(max_length=64, editable=False)
    used_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = _("recovery code")
        verbose_name_plural = _("recovery codes")
        indexes = [
            models.Index(fields=["user", "used_at"], name="recovery_user_used_idx"),
        ]

    def __str__(self) -> str:
        # Never the code or its hash.
        state = "used" if self.used_at else "unused"
        return f"Recovery code for {self.user_id} ({state})"


# ---------------------------------------------------------------------------
# Encryption
# ---------------------------------------------------------------------------


def _fernet() -> Fernet:
    key = getattr(settings, "MFA_ENCRYPTION_KEY", "") or ""
    if not key:
        # Defence in depth: `config/settings/hardened.py` already refuses to
        # boot a deployed environment without this, so reaching here means a
        # programming error in a settings module, not a request an attacker
        # can trigger. Fails closed either way.
        raise ImproperlyConfigured(
            "MFA_ENCRYPTION_KEY is not configured. See docs/environments.md."
        )
    return Fernet(key.encode("utf-8") if isinstance(key, str) else key)


def encrypt_secret(raw_secret: str) -> bytes:
    return _fernet().encrypt(raw_secret.encode("utf-8"))


def decrypt_secret(token: bytes) -> str | None:
    """Returns ``None`` rather than raising on a token that will not decrypt
    (a corrupted row, a rotated key) — a request to verify a TOTP code should
    answer "wrong code", not crash, for a fault that is the deployment's,
    never the caller's, to fix."""
    try:
        return _fernet().decrypt(bytes(token)).decode("utf-8")
    except InvalidToken:
        return None


# ---------------------------------------------------------------------------
# TOTP
# ---------------------------------------------------------------------------


def generate_totp_secret() -> str:
    return pyotp.random_base32()


def provisioning_uri(*, user, secret: str) -> str:
    """The ``otpauth://`` URI an authenticator app scans as a QR code."""
    totp = pyotp.TOTP(secret, digits=TOTP_DIGITS, interval=TOTP_STEP_SECONDS)
    return totp.provisioning_uri(name=user.email, issuer_name=TOTP_ISSUER)


def qr_svg(data: str) -> str:
    """``data`` rendered as an SVG QR code.

    Uses ``qrcode`` (already a dependency — ``apps.certificates.rendering``
    renders certificate-verification QR codes with the same library, as PNG)
    with its SVG image factory, so this adds no new dependency. SVG rather
    than PNG: the secret never touches disk as an image file, the string is
    small enough to return inline in the JSON response, and it scales
    cleanly in a modal at any size the frontend chooses.
    """
    import qrcode
    from qrcode.image.svg import SvgPathImage

    code = qrcode.QRCode(image_factory=SvgPathImage, box_size=8, border=2)
    code.add_data(data)
    code.make(fit=True)
    buffer = BytesIO()
    code.make_image().save(buffer)
    return buffer.getvalue().decode("utf-8")


def _current_step(at) -> int:
    return int(at.timestamp() // TOTP_STEP_SECONDS)


def _matched_step(*, secret: str, code: str, last_used_step: int | None) -> int | None:
    """The TOTP step ``code`` matches, or ``None``.

    Checks "now" and one step either side (``TOTP_VALID_WINDOW``), refusing
    any step at or before ``last_used_step`` — the replay guard applies
    before comparison, not after, so an already-spent code can never match
    twice even if the clock skew window would otherwise let it.
    """
    submitted = (code or "").strip()
    if not submitted:
        return None
    totp = pyotp.TOTP(secret, digits=TOTP_DIGITS, interval=TOTP_STEP_SECONDS)
    now = timezone.now()
    now_step = _current_step(now)
    floor = -1 if last_used_step is None else int(last_used_step)
    for offset in (0, -1, 1):
        step = now_step + offset
        if step <= floor:
            continue
        candidate = totp.at(now, counter_offset=offset)
        if pyotp.utils.strings_equal(candidate, submitted):
            return step
    return None


@transaction.atomic
def verify_totp_code(*, user, code: str) -> bool:
    """Check ``code`` against the user's confirmed device, if any.

    ``select_for_update`` on the device row: two concurrent verifications of
    the same step cannot both read the old ``last_used_step``, so both
    succeeding — the same replay ``verify_email_code`` already guards
    against for email codes — is not possible here either.
    """
    device = (
        MfaDevice.objects.select_for_update().filter(user=user, confirmed_at__isnull=False).first()
    )
    if device is None:
        return False
    secret = decrypt_secret(bytes(device.secret_encrypted))
    if secret is None:
        return False
    step = _matched_step(secret=secret, code=code, last_used_step=device.last_used_step)
    if step is None:
        return False
    device.last_used_step = step
    device.save(update_fields=["last_used_step", "updated_at"])
    return True


# ---------------------------------------------------------------------------
# Recovery codes
# ---------------------------------------------------------------------------

_RECOVERY_CODE_CLEAN_RE = re.compile(r"[^A-Z0-9]")


def _normalise_recovery_code(raw: str) -> str:
    return _RECOVERY_CODE_CLEAN_RE.sub("", (raw or "").upper())


def _hash_recovery_code(normalised: str) -> str:
    return sha256(normalised.encode("utf-8")).hexdigest()


def _generate_recovery_code() -> str:
    """Ten hex characters (40 bits), grouped for readability. Single-use and
    rate-limited by the same ``auth`` throttle as every other MFA guess, so
    this is comfortably past the point where brute force is the weak link."""
    raw = secrets.token_hex(5).upper()
    return f"{raw[:5]}-{raw[5:]}"


def issue_recovery_codes(*, user) -> list[str]:
    """Ten fresh codes, replacing (invalidating) every prior one.

    Deletes outright rather than soft-deleting — see the module and model
    docstrings: a recovery code that could be un-deleted back into validity
    would be a genuine MFA bypass, not a recoverable mistake.
    """
    RecoveryCode.objects.filter(user=user).delete()
    plain_codes: list[str] = []
    rows: list[RecoveryCode] = []
    for _index in range(RECOVERY_CODE_COUNT):
        plain = _generate_recovery_code()
        plain_codes.append(plain)
        rows.append(
            RecoveryCode(user=user, code_hash=_hash_recovery_code(_normalise_recovery_code(plain)))
        )
    RecoveryCode.objects.bulk_create(rows)
    return plain_codes


@transaction.atomic
def consume_recovery_code(*, user, code: str) -> bool:
    """Check and burn one recovery code. ``select_for_update`` plus the
    ``used_at__isnull=True`` filter is exactly ``verify_email_code``'s
    concurrency shape: a second simultaneous submission of the same code
    blocks on the row lock, then finds it already used."""
    normalised = _normalise_recovery_code(code)
    if not normalised:
        return False
    hashed = _hash_recovery_code(normalised)
    row = (
        RecoveryCode.objects.select_for_update()
        .filter(user=user, code_hash=hashed, used_at__isnull=True)
        .first()
    )
    if row is None:
        return False
    row.used_at = timezone.now()
    row.save(update_fields=["used_at", "updated_at"])
    return True


# ---------------------------------------------------------------------------
# Dispatch: one entry point login and step-up both call
# ---------------------------------------------------------------------------


def verify(*, user, method: str, code: str, purpose: str, request_ip: str | None = None) -> bool:
    """Check ``code`` by ``method`` for ``user``. ``purpose`` is ``"login"``
    or ``"step_up"`` and only matters for the email method, which reuses
    Phase 4's ``OneTimeCode`` and needs to know which of its two reserved
    purposes this is."""
    if method == MfaMethod.TOTP:
        return verify_totp_code(user=user, code=code)
    if method == MfaMethod.RECOVERY:
        return consume_recovery_code(user=user, code=code)
    if method == MfaMethod.EMAIL:
        from .otp import OtpPurpose, verify_email_code

        otp_purpose = OtpPurpose.LOGIN if purpose == "login" else OtpPurpose.STEP_UP
        return verify_email_code(user=user, purpose=otp_purpose, code=code, request_ip=request_ip)
    return False


# ---------------------------------------------------------------------------
# Enrolment / disable / regenerate
# ---------------------------------------------------------------------------


def _security_email(*, user, kind: str, title: str, body: str) -> None:
    """mfa.enrolled / mfa.disabled: informational, not a credential, so —
    unlike the OTP code itself — this goes through the ordinary notification
    outbox (``apps.notifications.services.notify``), the same as any other
    "something changed on your account" email.

    It must reach the user regardless of their notification preferences: a
    security event is not a subscription. ``NotificationCategory.SECURITY``
    has no matching ``email_*`` column on ``NotificationPreference`` — see
    that model's ``wants_email`` — so there is no toggle to bypass; the
    category simply never appears among the ones a preference can turn off.
    Only the institution-wide "email delivery" kill switch still applies,
    the same as it does to a locked-out admin's own broadcast — this is a
    channel-outage safeguard, not a per-user preference.
    """
    from apps.notifications.services import notify

    notify(recipient=user, kind=str(kind), title=title, body=body, send_email=True)


def start_enrolment(*, user) -> tuple[MfaDevice, str]:
    """Begin (or restart) TOTP enrolment. Returns the device row and the
    *raw* secret — the only moment it ever exists outside the encrypted
    column; the caller must return it in the response and hold it nowhere
    else (never logged, never audited — rule §13)."""
    existing = MfaDevice.objects.filter(user=user).first()
    if existing is not None and existing.is_confirmed:
        raise MfaEnrolmentConflict()

    secret = generate_totp_secret()
    encrypted = encrypt_secret(secret)
    if existing is not None:
        existing.secret_encrypted = encrypted
        existing.last_used_step = None
        existing.save(update_fields=["secret_encrypted", "last_used_step", "updated_at"])
        device = existing
    else:
        device = MfaDevice.objects.create(user=user, secret_encrypted=encrypted)
    return device, secret


@transaction.atomic
def confirm_enrolment(*, user, code: str) -> list[str]:
    """Prove possession of the enrolled secret; return ten recovery codes,
    shown exactly once (D-100's one-time-visibility spirit, same as an
    administrator's credential link)."""
    device = (
        MfaDevice.objects.select_for_update().filter(user=user, confirmed_at__isnull=True).first()
    )
    if device is None:
        raise MfaNoPendingEnrolment()

    secret = decrypt_secret(bytes(device.secret_encrypted))
    step = None if secret is None else _matched_step(secret=secret, code=code, last_used_step=None)
    if step is None:
        record(
            action=AuditAction.MFA_FAILED,
            actor=user,
            resource_type="mfa_device",
            resource_id=device.pk,
            result=AuditResult.FAILURE,
            context={"stage": "confirm"},
        )
        raise InvalidMfaCode()

    device.confirmed_at = timezone.now()
    device.last_used_step = step
    device.save(update_fields=["confirmed_at", "last_used_step", "updated_at"])

    codes = issue_recovery_codes(user=user)

    user.mfa_enrolled_at = timezone.now()
    user.save(update_fields=["mfa_enrolled_at"])

    record(
        action=AuditAction.MFA_CONFIRMED,
        actor=user,
        resource_type="mfa_device",
        resource_id=device.pk,
    )
    record(
        action=AuditAction.MFA_ENROLLED,
        actor=user,
        resource_type="mfa_device",
        resource_id=device.pk,
    )
    from apps.notifications.models import NotificationKind

    transaction.on_commit(
        lambda: _security_email(
            user=user,
            kind=NotificationKind.MFA_ENROLLED,
            title="Two-factor authentication turned on",
            body=(
                "An authenticator app was added to your account and ten recovery "
                "codes were issued. If this was not you, sign in and disable it, "
                "or contact your administrator immediately."
            ),
        )
    )
    return codes


def disable(*, user) -> None:
    """Remove the device and every recovery code — genuinely, not a soft
    delete (module docstring). Requires a fresh step-up; the caller (the
    view) checks that before calling this."""
    device = MfaDevice.objects.filter(user=user).first()
    if device is None:
        raise MfaNotEnabled()

    with transaction.atomic():
        device_id = device.pk
        device.delete()
        RecoveryCode.objects.filter(user=user).delete()
        user.mfa_enrolled_at = None
        user.save(update_fields=["mfa_enrolled_at"])
        record(
            action=AuditAction.MFA_DISABLED,
            actor=user,
            resource_type="mfa_device",
            resource_id=device_id,
        )
    from apps.notifications.models import NotificationKind

    transaction.on_commit(
        lambda: _security_email(
            user=user,
            kind=NotificationKind.MFA_DISABLED,
            title="Two-factor authentication turned off",
            body=(
                "Two-factor authentication was removed from your account, along "
                "with its recovery codes. If this was not you, contact your "
                "administrator immediately."
            ),
        )
    )


def regenerate_recovery_codes(*, user) -> list[str]:
    """Invalidate every existing recovery code and issue ten new ones.
    Requires a fresh step-up; the caller checks that before calling this."""
    if not has_confirmed_device(user=user):
        raise MfaNotEnabled()
    codes = issue_recovery_codes(user=user)
    record(
        action=AuditAction.MFA_RECOVERY_REGENERATED,
        actor=user,
        resource_type="user",
        resource_id=user.pk,
    )
    return codes


# ---------------------------------------------------------------------------
# "Is MFA required, and by what" — the login-time question
# ---------------------------------------------------------------------------


def has_confirmed_device(*, user) -> bool:
    return MfaDevice.objects.filter(user=user, confirmed_at__isnull=False).exists()


def _required_by_policy(*, user) -> bool:
    """Whether ``user``'s role is on the required list *and* their account
    is past its grace period.

    Grace-period anchor: the account's own ``date_joined``. This is a
    deliberate, narrow choice, made because ``DATA_MODEL.md`` allows exactly
    one new column on ``User`` for this phase (``mfa_enrolled_at``) — there
    is no second field free to record "when did the requirement start
    applying to this account". ``date_joined`` is the one timestamp every
    account already carries that is not itself evidence of enrolment, so a
    brand-new account gets a real `mfa.grace_days` window to enrol before
    its first login is forced into the pending-MFA branch, while an
    account that predates the policy is judged by its own age. The
    trade-off this accepts: turning `mfa_required_roles` on for a role does
    not itself re-arm a fresh grace window for that role's *existing*
    long-lived accounts — an admin account created two years ago is already
    past any `mfa.grace_days` value and is required immediately. That is
    consistent with treating the requirement as "how old must an account of
    this role be", not "how long since the policy last changed", which is
    both simpler and does not depend on when a policy row was last written
    (a value that resets to its default on `policy.reset` regardless of
    intent).
    """
    from apps.policies.resolver import policy

    required_roles = policy("authentication", "mfa_required_roles")
    if user.role not in required_roles:
        return False
    grace_days = policy("authentication", "mfa_grace_days")
    grace_until = user.date_joined + timedelta(days=grace_days)
    return timezone.now() >= grace_until


def is_required(*, user) -> bool:
    """Whether a correct password alone is enough, or MFA must follow."""
    return has_confirmed_device(user=user) or _required_by_policy(user=user)


def available_methods(*, user) -> list[str]:
    """Methods this user could complete a pending sign-in with, in the order
    the API always presents them: authenticator app first (the strongest and
    the one most people who have it will reach for), then email (always
    available to any active user), then recovery (only when unused codes
    remain)."""
    methods: list[str] = []
    if has_confirmed_device(user=user):
        methods.append(MfaMethod.TOTP)
    methods.append(MfaMethod.EMAIL)
    if RecoveryCode.objects.filter(user=user, used_at__isnull=True).exists():
        methods.append(MfaMethod.RECOVERY)
    return methods


# ---------------------------------------------------------------------------
# Pending-MFA session state
# ---------------------------------------------------------------------------


def start_pending(*, request, user) -> None:
    """Stamp the session as pending. ``django.contrib.auth.login`` is
    deliberately never called here — see the module docstring for why that
    alone is what keeps every other endpoint closed to this session."""
    request.session[PENDING_SESSION_KEY] = {
        "user_id": str(user.pk),
        "expires_at": (timezone.now() + timedelta(seconds=PENDING_TTL_SECONDS)).timestamp(),
    }
    request.session.modified = True


def get_pending_user(*, request) -> Any:
    """The user a pending session names, or ``None`` if there is no pending
    session, it has expired, or it names an account that no longer
    qualifies (deactivated, deleted) — any of which clears the marker."""
    data = request.session.get(PENDING_SESSION_KEY)
    if not isinstance(data, dict):
        return None
    expires_at = data.get("expires_at")
    if not expires_at or float(expires_at) < timezone.now().timestamp():
        clear_pending(request=request)
        return None

    from .models import User

    try:
        return User.objects.get(pk=data.get("user_id"), is_active=True)
    except (User.DoesNotExist, DjangoValidationError, ValueError, TypeError):
        clear_pending(request=request)
        return None


def clear_pending(*, request) -> None:
    if PENDING_SESSION_KEY in request.session:
        del request.session[PENDING_SESSION_KEY]
        request.session.modified = True


__all__ = [
    "PENDING_TTL_SECONDS",
    "RECOVERY_CODE_COUNT",
    "TOTP_ISSUER",
    "InvalidMfaCode",
    "MfaDevice",
    "MfaEnrolmentConflict",
    "MfaMethod",
    "MfaNoPendingEnrolment",
    "MfaNotEnabled",
    "RecoveryCode",
    "available_methods",
    "clear_pending",
    "confirm_enrolment",
    "consume_recovery_code",
    "decrypt_secret",
    "disable",
    "encrypt_secret",
    "generate_totp_secret",
    "get_pending_user",
    "has_confirmed_device",
    "is_required",
    "issue_recovery_codes",
    "provisioning_uri",
    "qr_svg",
    "regenerate_recovery_codes",
    "start_enrolment",
    "start_pending",
    "verify",
    "verify_totp_code",
]
