# Generated by Django 5.2.17 on 2026-09-01 03:05

import apps.common.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_code_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice, one answer'), ('multiple', 'Multiple choice, several answers'), ('true_false', 'True or false'), ('short_answer', 'Short answer'), ('long_answer', 'Long answer'), ('file', 'File upload')], default='mcq', max_length=14, verbose_name='type')),
                ('text', models.TextField(validators=[apps.common.validators.validate_no_control_characters], verbose_name='question')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=8, verbose_name='difficulty')),
                ('marks', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='marks')),
                ('negative_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deducted for a wrong answer when the exam has negative marking on.', max_digits=6, verbose_name='negative marks')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Used to draw a paper from a topic. Lower-case, no spaces.', size=None, verbose_name='tags')),
                ('answer_key', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Short-answer only. Compared case- and whitespace-insensitively.', size=None, verbose_name='accepted answers')),
                ('explanation', models.TextField(blank=True, help_text='Shown after results are published.', verbose_name='explanation')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('course', models.ForeignKey(blank=True, help_text='Leave empty for a question shared across every course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='courses.module')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500, verbose_name='option')),
                ('is_correct', models.BooleanField(default=False, verbose_name='correct')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'verbose_name': 'question option',
                'verbose_name_plural': 'question options',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['course', 'is_active'], name='question_course_active_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'difficulty'], name='question_type_diff_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('marks__gt', 0)), name='question_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('negative_marks__gte', 0)), name='question_negative_not_negative'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'position'], name='option_question_pos_idx'),
        ),
    ]
