# Generated by Django 5.2.17 on 2026-09-01 07:10

import apps.certificates.models
import apps.common.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True, verbose_name='certificate number')),
                ('verification_code', models.CharField(default=apps.certificates.models.new_verification_code, editable=False, help_text='What the public endpoint takes. Unguessable, and not the number.', max_length=64, unique=True, verbose_name='verification code')),
                ('student_name', models.CharField(max_length=200, verbose_name='student name')),
                ('student_code', models.CharField(max_length=20, verbose_name='student id')),
                ('course_title', models.CharField(max_length=200, verbose_name='course')),
                ('batch_code', models.CharField(max_length=20, verbose_name='batch')),
                ('completion_date', models.DateField(verbose_name='completion date')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked'), ('superseded', 'Superseded by a reissue')], default='issued', max_length=12, verbose_name='status')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='issued at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('revocation_reason', models.CharField(blank=True, max_length=300, verbose_name='reason')),
                ('reissue_reason', models.CharField(blank=True, max_length=300, verbose_name='reissue reason')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, validators=[apps.common.validators.validate_no_control_characters], verbose_name='name')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('institution_name', models.CharField(default='Grras Solutions', max_length=160, verbose_name='institution')),
                ('title', models.CharField(default='Certificate of Completion', max_length=120, verbose_name='heading')),
                ('body', models.TextField(default='This is to certify that {student_name} has successfully completed the course {course_title} on {completion_date}.', help_text='Placeholders: {student_name}, {course_title}, {completion_date}, {certificate_number}, {batch_code}, {institution_name}.', verbose_name='body')),
                ('signatory_name', models.CharField(blank=True, max_length=120, verbose_name='signatory')),
                ('signatory_title', models.CharField(blank=True, max_length=120, verbose_name='signatory title')),
                ('footer', models.CharField(blank=True, default='Verify this certificate at the address in the QR code.', max_length=200, verbose_name='footer')),
            ],
            options={
                'verbose_name': 'certificate template',
                'verbose_name_plural': 'certificate templates',
                'ordering': ('-is_default', 'name'),
            },
        ),
    ]
