# Generated by Django 5.2.17 on 2026-09-01 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='completion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='progress.coursecompletion'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='certificates.certificate'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.certificatetemplate'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='certificate_single_default_template'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status'], name='certificate_status_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student_code'], name='certificate_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'revoked'), _negated=True), ('revoked_at__isnull', False), _connector='OR'), name='certificate_revoked_has_a_time'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'issued')), fields=('completion',), name='certificate_one_live_per_completion'),
        ),
    ]
