# Generated by Django 5.2.17 on 2026-09-15 11:25

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0002_default_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('category', models.CharField(max_length=30, verbose_name='category')),
                ('key', models.CharField(max_length=60, verbose_name='key')),
                ('scope', models.CharField(choices=[('global', 'Institution-wide'), ('branch', 'Branch override')], default='global', max_length=10, verbose_name='scope')),
                ('value', models.JSONField(help_text='Validated against POLICY_SCHEMAS on write.', verbose_name='value')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('branch', models.ForeignKey(blank=True, help_text="Set only when scope is 'branch'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='organisation.branch')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'policies',
                'ordering': ('category', 'key', 'branch_id'),
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(verbose_name='version')),
                ('value', models.JSONField(verbose_name='value')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='reason')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policies.policy')),
            ],
            options={
                'verbose_name': 'policy version',
                'verbose_name_plural': 'policy versions',
                'ordering': ('-version',),
            },
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', True), ('scope', 'global')), models.Q(('branch__isnull', False), ('scope', 'branch')), _connector='OR'), name='policy_scope_matches_branch'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True), ('deleted_at__isnull', True)), fields=('category', 'key'), name='policy_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False), ('deleted_at__isnull', True)), fields=('category', 'key', 'branch'), name='policy_branch_unique'),
        ),
    ]
