# Generated by Django 5.2.17 on 2026-09-16 00:14

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('slug', models.CharField(max_length=60, verbose_name='slug')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('entity', models.CharField(choices=[('activity', 'Activity'), ('student', 'Student'), ('registration', 'Registration'), ('review', 'Review')], max_length=20, verbose_name='entity')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10, verbose_name='status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form definition',
                'verbose_name_plural': 'form definitions',
                'ordering': ('slug',),
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10, verbose_name='status')),
                ('schema_hash', models.CharField(blank=True, max_length=64, verbose_name='schema hash')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='forms.formversion')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='forms.formdefinition')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form version',
                'verbose_name_plural': 'form versions',
                'ordering': ('definition_id', '-number'),
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('values', models.JSONField(default=dict, verbose_name='values')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='forms.formversion')),
            ],
            options={
                'verbose_name': 'form response',
                'verbose_name_plural': 'form responses',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=60, verbose_name='key')),
                ('label', models.CharField(max_length=150, verbose_name='label')),
                ('help', models.CharField(blank=True, max_length=500, verbose_name='help text')),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'Date and time'), ('boolean', 'Boolean'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('file', 'File'), ('image', 'Image'), ('richtext', 'Rich text'), ('relation', 'Relation')], max_length=20, verbose_name='type')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('group', models.CharField(blank=True, max_length=60, verbose_name='group')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='options')),
                ('validation', models.JSONField(blank=True, default=dict, verbose_name='validation')),
                ('visible_to_student', models.BooleanField(default=False, verbose_name='visible to student')),
                ('performance_key', models.CharField(blank=True, default='', max_length=30, verbose_name='performance key')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.formversion')),
            ],
            options={
                'verbose_name': 'form field',
                'verbose_name_plural': 'form fields',
                'ordering': ('version_id', 'order'),
            },
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='form_definition_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='formversion',
            constraint=models.UniqueConstraint(fields=('definition', 'number'), name='form_version_number_unique'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['content_type', 'object_id'], name='form_response_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('version', 'key'), name='form_field_key_unique'),
        ),
    ]
