# Generated by Django 5.2.17 on 2026-10-01 13:57

import apps.forms.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('forms', '0002_seed_catalog'),
        ('organisation', '0002_default_branch'),
        ('students', '0008_alter_studentprofile_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='show_if',
            field=models.JSONField(blank=True, default=dict, verbose_name='show if'),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='entity',
            field=models.CharField(choices=[('activity', 'Activity'), ('student', 'Student'), ('registration', 'Registration'), ('review', 'Review'), ('enquiry', 'Enquiry'), ('general', 'General')], max_length=20, verbose_name='entity'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'Date and time'), ('boolean', 'Boolean'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('file', 'File'), ('image', 'Image'), ('richtext', 'Rich text'), ('relation', 'Relation'), ('time', 'Time'), ('rating', 'Rating'), ('consent', 'Consent'), ('hidden', 'Hidden value'), ('heading', 'Heading'), ('dependent_select', 'Dependent select')], max_length=20, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='FormUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.forms.models.form_upload_to, verbose_name='file')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='original name')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='extension')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='content type')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='size in bytes')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form upload',
                'verbose_name_plural': 'form uploads',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FormAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting to be filled'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='pending', max_length=12, verbose_name='status')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='due at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_assignments', to=settings.AUTH_USER_MODEL)),
                ('automation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_assignments', to='automation.automationrun')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisation.branch')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='forms.formdefinition')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='forms.formresponse')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_assignments', to='students.studentprofile')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='forms.formversion')),
            ],
            options={
                'verbose_name': 'form assignment',
                'verbose_name_plural': 'form assignments',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['assigned_to', 'status', 'due_at'], name='form_assignment_inbox_idx'), models.Index(fields=['definition', 'status'], name='form_assignment_form_idx')],
            },
        ),
    ]
