# Generated by Django 5.2.17 on 2026-10-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiries", "0001_initial"),
        ("forms", "0004_seed_enquiry_forms"),
    ]

    operations = [
        migrations.AddField(
            model_name="formassignment",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_assignments",
                to="enquiries.enquiry",
            ),
        ),
    ]
