# Generated by Django 5.2.17 on 2026-10-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formassignment_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdefinition',
            name='entity',
            field=models.CharField(choices=[('activity', 'Activity'), ('student', 'Student'), ('registration', 'Registration'), ('review', 'Review'), ('enquiry', 'Enquiry'), ('general', 'General'), ('dsr', 'Class report')], max_length=20, verbose_name='entity'),
        ),
    ]
