# Generated by Django 5.2.17 on 2026-09-07 22:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_color', models.CharField(blank=True, default='', help_text='Hex, e.g. #EF7220. Blank uses the built-in Grras palette. The interface derives a darker shade for buttons and links so text on them stays legible, whatever colour is chosen.', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a hex colour such as #EF7220.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='brand colour')),
                ('display_name', models.CharField(blank=True, default='', help_text='Shown in the interface. Blank uses the product name.', max_length=120, verbose_name='institution name')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'branding',
                'verbose_name_plural': 'branding',
            },
        ),
    ]
