# Generated by Django 5.2.17 on 2026-09-01 03:05

import apps.common.uploads
import apps.common.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_options', models.JSONField(blank=True, default=list, verbose_name='selected options')),
                ('text_answer', models.TextField(blank=True, verbose_name='written answer')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.common.uploads.submission_upload_to, verbose_name='file')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='correct')),
                ('awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='marks awarded')),
                ('needs_manual_marking', models.BooleanField(default=False, verbose_name='needs marking')),
                ('marker_feedback', models.TextField(blank=True, verbose_name='marker feedback')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='answered at')),
            ],
            options={
                'verbose_name': 'attempt answer',
                'verbose_name_plural': 'attempt answers',
                'ordering': ('attempt_question__position',),
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='marks')),
                ('negative_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='negative marks')),
                ('option_order', models.JSONField(blank=True, default=list, verbose_name='option order')),
            ],
            options={
                'verbose_name': 'attempt question',
                'verbose_name_plural': 'attempt questions',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='code')),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='opens at')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='closes at')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='duration in minutes')),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, verbose_name='maximum attempts')),
                ('passing_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to take the passing rule from the academic configuration.', max_digits=6, null=True, verbose_name='passing marks')),
                ('negative_marking', models.BooleanField(default=False, help_text="Deduct each question's negative marks for a wrong answer.", verbose_name='negative marking')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='shuffle questions')),
                ('shuffle_options', models.BooleanField(default=True, verbose_name='shuffle options')),
                ('results_published', models.BooleanField(default=False, help_text='Until this is on, a candidate sees that they submitted and nothing more.', verbose_name='results published')),
                ('results_published_at', models.DateTimeField(blank=True, null=True, verbose_name='results published at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=12, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
            ],
            options={
                'verbose_name': 'examination',
                'verbose_name_plural': 'examinations',
                'ordering': ('-opens_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='attempt')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted, awaiting marking'), ('graded', 'Graded'), ('expired', 'Time expired')], default='in_progress', max_length=12, verbose_name='status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='started at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='graded at')),
                ('auto_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='auto-marked score')),
                ('manual_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='manually marked score')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='total score')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='paper total')),
            ],
            options={
                'verbose_name': 'examination attempt',
                'verbose_name_plural': 'examination attempts',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('question_count', models.PositiveSmallIntegerField(default=5, verbose_name='questions to draw')),
                ('difficulty', models.CharField(blank=True, max_length=8, verbose_name='difficulty')),
                ('question_type', models.CharField(blank=True, max_length=14, verbose_name='type')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
            ],
            options={
                'verbose_name': 'examination section',
                'verbose_name_plural': 'examination sections',
                'ordering': ('position', 'created_at'),
            },
        ),
    ]
