# Generated by Django 5.2.17 on 2026-09-01 03:05

import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_batch_code_sequence'),
        ('courses', '0002_course_code_sequence'),
        ('enrollments', '0001_initial'),
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_appearances', to='questions.question'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='attempt_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='exams.attemptquestion'),
        ),
        migrations.AddField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examattempt'),
        ),
        migrations.AddField(
            model_name='examsection',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawn', to='exams.examsection'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['batch', 'status'], name='exam_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['opens_at'], name='exam_opens_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1)), name='exam_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='exam_attempts_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__isnull', True), ('opens_at__isnull', True), ('closes_at__gt', models.F('opens_at')), _connector='OR'), name='exam_window_ordered'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'status'], name='attempt_exam_status_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['enrollment'], name='attempt_enrolment_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'enrollment', 'attempt_number'), name='attempt_one_row_per_sitting'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='attempt_number_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.CheckConstraint(condition=models.Q(('question_count__gte', 1)), name='section_draws_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('exam', 'position'), name='section_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('attempt', 'position'), name='attemptquestion_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='attemptquestion_no_duplicates'),
        ),
    ]
