# Generated by Django 5.2.17 on 2026-09-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_code_sequence'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examattempt',
            name='attempt_enrolment_idx',
        ),
    ]
