# Generated by Django 5.2.17 on 2026-08-31 09:17

import apps.accounts.managers
import apps.common.validators
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Used to sign in. Stored lower-cased.', max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100, validators=[apps.common.validators.validate_person_name], verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, validators=[apps.common.validators.validate_person_name], verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.common.validators.validate_phone_number], verbose_name='phone')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('trainer', 'Trainer'), ('student', 'Student')], db_index=True, default='student', help_text='Authoritative role used for server-side authorization.', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate instead of deleting to preserve audit history.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('email',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_unique')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
