# Generated by Django 5.2.17 on 2026-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Administrator'), ('manager', 'Manager'), ('counsellor', 'Counsellor'), ('trainer', 'Trainer'), ('student', 'Student')], db_index=True, default='student', help_text='Authoritative role used for server-side authorization.', max_length=20, verbose_name='role'),
        ),
    ]
