# Generated by Django 5.2.17 on 2026-09-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The centre this account belongs to. Empty means the account carries no centre, which for everybody but a superadmin means it sees nothing rather than everything. Which roles may leave it empty is enforced by apps.accounts.services rather than by the column, so that history survives a centre being closed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organisation.branch', verbose_name='branch'),
        ),
    ]
