# Generated by Django 5.2.17 on 2026-09-15 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_branch'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text="A configured role of the same kind as `role`, whose permission set replaces the kind's default (ADR-01). Empty means the system role.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='authorization.role', verbose_name='custom role'),
        ),
    ]
