# Generated by Django 5.2.17 on 2026-09-15 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_roles_as_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('step_up', 'Step-up authentication'), ('login', 'Sign-in second factor'), ('enrol', 'Enrolment verification')], db_index=True, max_length=20)),
                ('code_hash', models.CharField(editable=False, max_length=64)),
                ('salt', models.CharField(editable=False, max_length=32)),
                ('sent_to', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'one-time code',
                'verbose_name_plural': 'one-time codes',
                'indexes': [models.Index(fields=['user', 'purpose', 'created_at'], name='otc_user_purpose_time_idx')],
            },
        ),
    ]
