# Generated by Django 5.2.17 on 2026-09-15 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otp_one_time_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enrolled_at',
            field=models.DateTimeField(blank=True, help_text='Set once a TOTP device is confirmed (ADR-05); cleared on disable. The one column this phase adds to User — see apps.accounts.mfa for the device and recovery-code tables themselves.', null=True, verbose_name='MFA enrolled at'),
        ),
        migrations.CreateModel(
            name='MfaDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_encrypted', models.BinaryField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_step', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(default='Authenticator app', max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA device',
                'verbose_name_plural': 'MFA devices',
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(editable=False, max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recovery code',
                'verbose_name_plural': 'recovery codes',
                'indexes': [models.Index(fields=['user', 'used_at'], name='recovery_user_used_idx')],
            },
        ),
    ]
