# Generated by Django 5.2.17 on 2026-09-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False, help_text='Explicit consent to receive WhatsApp messages at `phone` (ERP Phase 19). The WhatsApp channel refuses to send to anyone without this set, regardless of what a template or a manual send names as the recipient.', verbose_name='WhatsApp opt-in'),
        ),
    ]
