# Generated by Django 5.2.17 on 2026-09-06 21:20

import apps.common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short identifier an operator chooses, e.g. JAI or PUNE.', max_length=20, unique=True, validators=[apps.common.validators.validate_no_control_characters], verbose_name='code')),
                ('name', models.CharField(max_length=120, validators=[apps.common.validators.validate_no_control_characters], verbose_name='name')),
                ('city', models.CharField(blank=True, max_length=80, validators=[apps.common.validators.validate_no_control_characters], verbose_name='city')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='A closed centre keeps its people and classes readable; it is simply not offered when somebody is choosing where to put a new record.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ('code',),
                'indexes': [models.Index(fields=['is_active', 'code'], name='branch_active_code_idx')],
            },
        ),
    ]
