# Generated by Django 5.2.17 on 2026-08-31 22:28

import apps.common.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0002_assignment_code_sequence'),
        ('batches', '0002_batch_code_sequence'),
        ('courses', '0002_course_code_sequence'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='code')),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('weekly_test', 'Weekly test'), ('practice', 'Practice test'), ('mock', 'Mock test'), ('other', 'Other assessment')], default='weekly_test', max_length=20, verbose_name='category')),
                ('delivery', models.CharField(choices=[('external_link', 'External link'), ('file_upload', 'File upload'), ('offline', 'Offline / in class')], default='external_link', max_length=20, verbose_name='delivery')),
                ('external_url', models.URLField(blank=True, help_text='Where the test is taken, for an externally delivered assessment.', max_length=500, verbose_name='external URL')),
                ('external_provider', models.CharField(blank=True, help_text="Free-text label, e.g. 'Google Forms'. Nothing is integrated with it.", max_length=60, verbose_name='provider')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='scheduled for')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duration in minutes')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='opens at')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='closes at')),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, verbose_name='maximum marks')),
                ('passing_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='passing marks')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=12, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('backing_assignment', models.OneToOneField(blank=True, help_text='Created automatically for a file-upload assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backed_assessment', to='assignments.assignment')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='batches.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='courses.module')),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'ordering': ('-scheduled_for', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ResultImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='rows read')),
                ('valid_count', models.PositiveIntegerField(default=0, verbose_name='rows that would apply')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='rows with problems')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='results created')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='results updated')),
                ('status', models.CharField(choices=[('preview', 'Awaiting confirmation'), ('confirmed', 'Applied'), ('rejected', 'Rejected'), ('failed', 'Failed validation')], default='preview', max_length=12, verbose_name='status')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='report')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='assessments.assessment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'result import',
                'verbose_name_plural': 'result imports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='marks obtained')),
                ('is_absent', models.BooleanField(default=False, verbose_name='absent')),
                ('remarks', models.CharField(blank=True, max_length=500, verbose_name='remarks')),
                ('source', models.CharField(choices=[('manual', 'Entered by staff'), ('import', 'Imported from a file'), ('graded', 'Graded in the LMS')], default='manual', max_length=10, verbose_name='source')),
                ('recorded_at', models.DateTimeField(auto_now=True, verbose_name='recorded at')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='enrollments.enrollment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_recorded', to=settings.AUTH_USER_MODEL)),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='assessments.resultimport')),
            ],
            options={
                'verbose_name': 'assessment result',
                'verbose_name_plural': 'assessment results',
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['batch', 'status'], name='assessment_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['course', 'category'], name='assessment_course_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['scheduled_for'], name='assessment_scheduled_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_marks__gt', 0)), name='assessment_max_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('passing_marks__isnull', True), ('passing_marks__lte', models.F('max_marks')), _connector='OR'), name='assessment_passing_within_max'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery', 'external_link'), _negated=True), models.Q(('external_url', ''), _negated=True), _connector='OR'), name='assessment_external_needs_url'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('delivery', 'file_upload'), ('backing_assignment__isnull', True), _connector='OR'), name='assessment_backing_only_for_upload'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__isnull', True), ('opens_at__isnull', True), ('closes_at__gte', models.F('opens_at')), _connector='OR'), name='assessment_window_ordered'),
        ),
        migrations.AddIndex(
            model_name='resultimport',
            index=models.Index(fields=['assessment', 'status'], name='import_assessment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['assessment', 'is_absent'], name='result_assessment_abs_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['enrollment'], name='result_enrollment_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(fields=('assessment', 'enrollment'), name='result_one_per_student_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('marks_obtained__isnull', True), ('marks_obtained__gte', 0), _connector='OR'), name='result_marks_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_absent', True), ('marks_obtained__isnull', True)), ('is_absent', False), _connector='OR'), name='result_absent_has_no_marks'),
        ),
    ]
