# Generated by Django 5.2.17 on 2026-09-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_code_sequence'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assessmentresult',
            name='result_enrollment_idx',
        ),
    ]
