# Generated by Django 5.2.17 on 2026-08-31 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_code_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('global', 'Institution-wide'), ('course', 'Course override')], default='global', max_length=10, verbose_name='scope')),
                ('minimum_attendance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='minimum attendance %')),
                ('attendance_required_for_completion', models.BooleanField(blank=True, null=True, verbose_name='attendance required to complete')),
                ('passing_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Used whenever a piece of work does not set its own passing mark.', max_digits=5, null=True, verbose_name='passing %')),
                ('assignment_default_max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='default assignment marks')),
                ('assignment_allow_late', models.BooleanField(blank=True, null=True, verbose_name='allow late submission by default')),
                ('assignment_default_max_attempts', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='default assignment attempts')),
                ('assignment_required_for_completion', models.BooleanField(blank=True, null=True, verbose_name='assignments required to complete')),
                ('minimum_assignment_completion_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='minimum assignments completed %')),
                ('test_default_max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='default test marks')),
                ('tests_required_for_completion', models.BooleanField(blank=True, null=True, verbose_name='tests required to complete')),
                ('minimum_test_average_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='minimum test average %')),
                ('minimum_lesson_completion_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='minimum lessons completed %')),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_policy', to='courses.course')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'academic policy',
                'verbose_name_plural': 'academic policies',
                'ordering': ('scope', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'global')), fields=('scope',), name='policy_single_global_row'), models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', True), ('scope', 'global')), models.Q(('course__isnull', False), ('scope', 'course')), _connector='OR'), name='policy_scope_matches_course')],
            },
        ),
    ]
