# Generated by Django 5.2.17 on 2026-09-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpolicy',
            name='final_exam_required_for_completion',
            field=models.BooleanField(blank=True, help_text='Off by default: not every course ends in an examination.', null=True, verbose_name='final examination must be passed'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='lessons_required_for_completion',
            field=models.BooleanField(blank=True, help_text='Turn off for a cohort taught entirely offline (§6.5).', null=True, verbose_name='lessons required to complete'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='minimum_test_completion_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="How many of the batch's tests must have been sat, as opposed to passed.", max_digits=5, null=True, verbose_name='minimum tests taken %'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='projects_required_for_completion',
            field=models.BooleanField(blank=True, null=True, verbose_name='required projects must be finished'),
        ),
    ]
