# Generated by Django 5.2.17 on 2026-09-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicpolicy_final_exam_required_for_completion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpolicy',
            name='batch_directory_visible',
            field=models.BooleanField(blank=True, help_text='Names and student ids only — never contact details (§7.7).', null=True, verbose_name='students may see their classmates'),
        ),
    ]
