# Generated by Django 5.2.17 on 2026-09-01 10:26

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicpolicy_batch_directory_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpolicy',
            name='grade_bands',
            field=models.JSONField(blank=True, default=list, help_text='Percentage thresholds, highest first. Empty means the built-in bands.', verbose_name='grade bands'),
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, validators=[apps.common.validators.validate_no_control_characters], verbose_name='name')),
                ('kind', models.CharField(choices=[('term', 'Term'), ('holiday', 'Holiday'), ('exam_week', 'Examination week'), ('other', 'Other')], default='holiday', max_length=10, verbose_name='kind')),
                ('start_date', models.DateField(verbose_name='from')),
                ('end_date', models.DateField(verbose_name='to')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'academic calendar entry',
                'verbose_name_plural': 'academic calendar',
                'ordering': ('start_date', 'name'),
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='academic_event_range_idx'), models.Index(fields=['kind'], name='academic_event_kind_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='academic_event_dates_ordered')],
            },
        ),
    ]
