# Generated by Django 5.2.17 on 2026-09-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicpolicy_grade_bands_academicevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpolicy',
            name='risk_assessment_average_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Below this weekly-test average, a student is flagged at risk.', max_digits=5, null=True, verbose_name='assessment average risk threshold %'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='risk_attendance_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Below this attendance percentage, a student is flagged at risk.', max_digits=5, null=True, verbose_name='attendance risk threshold %'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='risk_missed_assignments',
            field=models.PositiveSmallIntegerField(blank=True, help_text='This many overdue assignments with no submission at all flags a student at risk.', null=True, verbose_name='missed assignments risk threshold'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='risk_progress_variance_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="How far behind the schedule implied by the batch's dates a student's lesson progress may fall before they are flagged at risk.", max_digits=5, null=True, verbose_name='progress variance risk threshold %'),
        ),
    ]
