# Generated by Django 5.2.17 on 2026-09-16 23:32

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organisation', '0002_default_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('trigger', models.CharField(choices=[('ACTIVITY_COMPLETED', 'Activity completed'), ('ACTIVITY_OVERDUE', 'Activity overdue'), ('ASSESSMENT_FAILED', 'Assessment failed'), ('ATTENDANCE_THRESHOLD', 'Attendance crossed threshold'), ('PROJECT_OVERDUE', 'Project overdue'), ('ASSIGNMENT_OVERDUE', 'Assignment overdue'), ('RISK_CHANGED', 'Risk level or triggered rules changed')], max_length=40, verbose_name='trigger')),
                ('conditions', models.JSONField(blank=True, default=list, help_text='A list of {path, op, value}, ANDed together.', verbose_name='conditions')),
                ('actions', models.JSONField(blank=True, default=list, help_text='A list of {type, params}, executed in order when conditions hold.', verbose_name='actions')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], default='draft', max_length=10, verbose_name='status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_system', models.BooleanField(default=False, help_text='Seeded at install. Provenance only — never locked, always editable.', verbose_name='system rule')),
                ('branch', models.ForeignKey(blank=True, help_text='Null applies the rule at every centre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='organisation.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'automation rule',
                'verbose_name_plural': 'automation rules',
                'ordering': ('name',),
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('ACTIVITY_COMPLETED', 'Activity completed'), ('ACTIVITY_OVERDUE', 'Activity overdue'), ('ASSESSMENT_FAILED', 'Assessment failed'), ('ATTENDANCE_THRESHOLD', 'Attendance crossed threshold'), ('PROJECT_OVERDUE', 'Project overdue'), ('ASSIGNMENT_OVERDUE', 'Assignment overdue'), ('RISK_CHANGED', 'Risk level or triggered rules changed')], max_length=40, verbose_name='trigger')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('occurrence_key', models.CharField(max_length=80, verbose_name='occurrence key')),
                ('depth', models.SmallIntegerField(default=0, verbose_name='depth')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ran', 'Ran'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=10, verbose_name='status')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='result')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('rule_version', models.PositiveIntegerField(default=1, help_text="The rule's version at the moment this run happened (ADR-13).", verbose_name='rule version')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automationrule')),
            ],
            options={
                'verbose_name': 'automation run',
                'verbose_name_plural': 'automation runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['trigger', 'status'], name='autorule_trigger_status_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['content_type', 'object_id'], name='autorun_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['rule', 'created_at'], name='autorun_rule_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationrun',
            constraint=models.UniqueConstraint(fields=('rule', 'occurrence_key'), name='automation_run_rule_occurrence_unique'),
        ),
    ]
