# Generated by Django 5.2.17 on 2026-09-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_seed_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Provenance only — never locked, always editable. Not currently set anywhere (the seeded rows are created with this False); reserved for future use.', verbose_name='system rule'),
        ),
    ]
