# Generated by Django 5.2.17 on 2026-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0003_alter_automationrule_is_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationrule",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("ACTIVITY_COMPLETED", "Activity completed"),
                    ("ACTIVITY_OVERDUE", "Activity overdue"),
                    ("ASSESSMENT_FAILED", "Assessment failed"),
                    ("ATTENDANCE_THRESHOLD", "Attendance crossed threshold"),
                    ("PROJECT_OVERDUE", "Project overdue"),
                    ("ASSIGNMENT_OVERDUE", "Assignment overdue"),
                    ("RISK_CHANGED", "Risk level or triggered rules changed"),
                    ("FORM_SUBMITTED", "Form submitted"),
                    ("ENQUIRY_CREATED", "Enquiry created"),
                    ("ENQUIRY_STAGE_CHANGED", "Enquiry stage changed"),
                    ("ENQUIRY_UPDATED", "Enquiry updated"),
                ],
                max_length=40,
                verbose_name="trigger",
            ),
        ),
        migrations.AlterField(
            model_name="automationrun",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("ACTIVITY_COMPLETED", "Activity completed"),
                    ("ACTIVITY_OVERDUE", "Activity overdue"),
                    ("ASSESSMENT_FAILED", "Assessment failed"),
                    ("ATTENDANCE_THRESHOLD", "Attendance crossed threshold"),
                    ("PROJECT_OVERDUE", "Project overdue"),
                    ("ASSIGNMENT_OVERDUE", "Assignment overdue"),
                    ("RISK_CHANGED", "Risk level or triggered rules changed"),
                    ("FORM_SUBMITTED", "Form submitted"),
                    ("ENQUIRY_CREATED", "Enquiry created"),
                    ("ENQUIRY_STAGE_CHANGED", "Enquiry stage changed"),
                    ("ENQUIRY_UPDATED", "Enquiry updated"),
                ],
                max_length=40,
                verbose_name="trigger",
            ),
        ),
    ]
