# Generated by Django 5.2.17 on 2026-08-31 12:28

import apps.common.uploads
import apps.common.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('slug', models.SlugField(help_text='Unique within its module.', max_length=160, validators=[apps.common.validators.validate_slug_value], verbose_name='slug')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='description')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('document', 'Document'), ('external_link', 'External link')], db_index=True, default='text', max_length=20, verbose_name='content type')),
                ('text_content', models.TextField(blank=True, help_text='Markdown. Rendered as text, never as HTML.', verbose_name='text content')),
                ('external_url', models.URLField(blank=True, help_text='Must be https. Opened in a new tab with noopener.', max_length=500, verbose_name='external URL')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='duration (minutes)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('is_preview', models.BooleanField(default=False, help_text='Readable without enrolment. The sample a prospective student sees.', verbose_name='free preview')),
                ('is_required', models.BooleanField(default=True, help_text='Optional lessons are supplementary material.', verbose_name='required')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('external_url', 'External URL'), ('s3', 'S3-compatible object storage'), ('managed', 'Managed video service')], default='external_url', max_length=20, verbose_name='provider')),
                ('asset_identifier', models.CharField(blank=True, help_text='Provider-side id: an object key, or a managed-service asset id.', max_length=255, verbose_name='asset identifier')),
                ('source_url', models.URLField(blank=True, help_text='Playable URL for the external-URL provider. Not returned in listings.', max_length=500, verbose_name='source URL')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='thumbnail URL')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(86400)], verbose_name='duration (seconds)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'video asset',
                'verbose_name_plural': 'video assets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[apps.common.validators.validate_no_control_characters], verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-safe identifier. Must be unique across all categories.', max_length=120, unique=True, validators=[apps.common.validators.validate_slug_value], verbose_name='slug')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive categories are hidden from the catalogue but keep their courses.', verbose_name='active')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('position', 'name'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='category_slug_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Human-readable identifier, e.g. GRS-C-00013. Allocated by the system.', max_length=20, unique=True, verbose_name='course code')),
                ('slug', models.SlugField(help_text='URL identifier. Stable once published — changing it breaks shared links.', max_length=160, unique=True, validators=[apps.common.validators.validate_slug_value], verbose_name='slug')),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('short_description', models.CharField(blank=True, help_text='One line, shown on catalogue cards.', max_length=300, verbose_name='short description')),
                ('description', models.TextField(blank=True, max_length=8000, verbose_name='full description')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.common.uploads.course_thumbnail_upload_to, verbose_name='thumbnail')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20, verbose_name='difficulty')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(525600)], verbose_name='estimated duration (minutes)')),
                ('learning_objectives', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=20, verbose_name='learning objectives')),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=20, verbose_name='prerequisites')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('visibility', models.CharField(choices=[('public', 'Public — listed in the catalogue'), ('internal', 'Internal — signed-in users only'), ('private', 'Private — assigned people only')], db_index=True, default='public', max_length=20, verbose_name='visibility')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='first published at')),
                ('content_updated_at', models.DateTimeField(blank=True, help_text='Set whenever a module, lesson or resource changes. Makes edits to a published course visible to reviewers.', null=True, verbose_name='content last changed at')),
                ('category', models.ForeignKey(help_text='Protected: deleting a category with courses would orphan them.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner — edit content and change status'), ('editor', 'Editor — edit content, cannot publish')], default='editor', max_length=20, verbose_name='role')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course assignment',
                'verbose_name_plural': 'course assignments',
                'ordering': ('course', 'user'),
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('kind', models.CharField(choices=[('file', 'File'), ('link', 'External link')], default='file', max_length=20, verbose_name='kind')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.common.uploads.resource_upload_to, verbose_name='file')),
                ('original_filename', models.CharField(blank=True, help_text='What the uploader called it. Display only — never used as a path.', max_length=255, verbose_name='original filename')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='content type')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='size in bytes')),
                ('external_url', models.URLField(blank=True, max_length=500, verbose_name='external URL')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('is_downloadable', models.BooleanField(default=True, help_text='When off, the resource is listed but the file is not served.', verbose_name='downloadable')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_resources_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lesson resource',
                'verbose_name_plural': 'lesson resources',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='description')),
                ('position', models.PositiveIntegerField(default=0, help_text='Explicit order within the course, from 0.', verbose_name='position')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('is_visible', models.BooleanField(default=True, help_text='Hide a finished module without unpublishing it.', verbose_name='visible')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='courses.videoasset'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'visibility', '-created_at'], name='course_catalog_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'status'], name='course_category_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='course_slug_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['user', 'course'], name='assignment_user_course_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='course_assignment_unique'),
        ),
        migrations.AddIndex(
            model_name='lessonresource',
            index=models.Index(fields=['lesson', 'position'], name='resource_lesson_position_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonresource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('kind', 'file')), ('kind', 'link'), _connector='OR'), name='resource_file_present_for_file_kind'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'position'], name='module_course_position_idx'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('course', 'position'), name='module_position_unique'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'position'], name='lesson_module_position_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('module', 'position'), name='lesson_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='lesson_slug_unique'),
        ),
    ]
