# Generated by Django 5.2.17 on 2026-09-14 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_code_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='default fee'),
        ),
    ]
