# Generated by Django 5.2.17 on 2026-09-14 11:16

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_default_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'base_manager_name': 'all_objects', 'ordering': ('position', 'created_at'), 'verbose_name': 'lesson', 'verbose_name_plural': 'lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonresource',
            options={'base_manager_name': 'all_objects', 'ordering': ('position', 'created_at'), 'verbose_name': 'lesson resource', 'verbose_name_plural': 'lesson resources'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'base_manager_name': 'all_objects', 'ordering': ('position', 'created_at'), 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelManagers(
            name='lesson',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lessonresource',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='module',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='delete_reason',
            field=models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='delete_reason',
            field=models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='delete_reason',
            field=models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion'),
        ),
        migrations.AddField(
            model_name='module',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='module',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
