# Generated by Django 5.2.17 on 2026-09-14 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='lesson_position_unique',
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='lesson_slug_unique',
        ),
        migrations.RemoveConstraint(
            model_name='module',
            name='module_position_unique',
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('module', 'position'), name='lesson_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('module', 'slug'), name='lesson_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('course', 'position'), name='module_position_unique'),
        ),
    ]
