# Generated by Django 5.2.17 on 2026-09-01 09:09

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_batch_delivery_mode'),
        ('courses', '0002_course_code_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('course', 'A course'), ('batch', 'A batch'), ('selected', 'Selected people')], default='batch', max_length=10, verbose_name='audience')),
                ('is_pinned', models.BooleanField(default=False, help_text='Kept at the top of the noticeboard.', verbose_name='pinned')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this it drops off the noticeboard. Leave empty to keep it.', null=True, verbose_name='expires at')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='batches.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, help_text="Only for the 'selected people' audience.", related_name='announcements_addressed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcements',
                'ordering': ('-is_pinned', '-published_at', '-created_at'),
                'indexes': [models.Index(fields=['status', '-published_at'], name='announcement_live_idx'), models.Index(fields=['batch'], name='announcement_batch_idx'), models.Index(fields=['course'], name='announcement_course_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('audience', 'everyone'), ('batch__isnull', True), ('course__isnull', True)), models.Q(('audience', 'course'), ('batch__isnull', True), ('course__isnull', False)), models.Q(('audience', 'batch'), ('batch__isnull', False)), models.Q(('audience', 'selected'), ('batch__isnull', True), ('course__isnull', True)), _connector='OR'), name='announcement_audience_matches_target')],
            },
        ),
    ]
