# Generated by Django 5.2.17 on 2026-09-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcement_batch_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcement_course_idx',
        ),
    ]
