# Generated by Django 5.2.17 on 2026-09-14 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_drop_redundant_fk_indexes'),
        ('batches', '0007_alter_batch_branch'),
        ('courses', '0005_partial_uniqueness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='announcement',
            name='announcement_audience_matches_target',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('course', 'A course'), ('batch', 'A batch'), ('selected', 'Selected people'), ('trainers', 'Trainers at my centre')], default='batch', max_length=10, verbose_name='audience'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience', 'everyone'), ('batch__isnull', True), ('course__isnull', True)), models.Q(('audience', 'course'), ('batch__isnull', True), ('course__isnull', False)), models.Q(('audience', 'batch'), ('batch__isnull', False)), models.Q(('audience', 'selected'), ('batch__isnull', True), ('course__isnull', True)), models.Q(('audience', 'trainers'), ('batch__isnull', True), ('course__isnull', True)), _connector='OR'), name='announcement_audience_matches_target'),
        ),
    ]
