# Generated by Django 5.2.17 on 2026-09-17 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_options_and_more'),
        ('authorization', '0003_scopes_and_locking'),
        ('batches', '0007_alter_batch_branch'),
        ('courses', '0005_partial_uniqueness'),
        ('organisation', '0002_default_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='announcement',
            name='announcement_audience_matches_target',
        ),
        migrations.AddField(
            model_name='announcement',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Only for the 'branch' audience: everyone at this one centre.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='organisation.branch'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='When a scheduled announcement is published automatically.', null=True, verbose_name='publish at'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='role',
            field=models.ForeignKey(blank=True, help_text="Only for the 'role' audience. Matched by the role's kind, not its id.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='authorization.role'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('course', 'A course'), ('batch', 'A batch'), ('selected', 'Selected people'), ('trainers', 'Trainers at my centre'), ('role', 'Everyone holding a role'), ('branch', 'Everyone at a centre')], default='batch', max_length=10, verbose_name='audience'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='draft', max_length=10, verbose_name='status'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience', 'everyone'), ('batch__isnull', True), ('branch__isnull', True), ('course__isnull', True), ('role__isnull', True)), models.Q(('audience', 'course'), ('branch__isnull', True), ('course__isnull', False), ('role__isnull', True)), models.Q(('audience', 'batch'), ('batch__isnull', False), ('branch__isnull', True), ('role__isnull', True)), models.Q(('audience', 'selected'), ('batch__isnull', True), ('branch__isnull', True), ('course__isnull', True), ('role__isnull', True)), models.Q(('audience', 'trainers'), ('batch__isnull', True), ('branch__isnull', True), ('course__isnull', True), ('role__isnull', True)), models.Q(('audience', 'role'), ('batch__isnull', True), ('branch__isnull', True), ('course__isnull', True), ('role__isnull', False)), models.Q(('audience', 'branch'), ('batch__isnull', True), ('branch__isnull', False), ('course__isnull', True), ('role__isnull', True)), _connector='OR'), name='announcement_audience_matches_target'),
        ),
    ]
