# Generated by Django 5.2.17 on 2026-09-01 09:09

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_batch_delivery_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('is_closed', models.BooleanField(default=False, help_text='Closed threads are readable but take no replies.', verbose_name='closed')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('reply_count', models.PositiveIntegerField(default=0, verbose_name='replies')),
                ('last_reply_at', models.DateTimeField(blank=True, null=True, verbose_name='last reply')),
                ('has_trainer_reply', models.BooleanField(default=False, verbose_name='answered by a trainer')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='batches.batch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads_closed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'discussion thread',
                'verbose_name_plural': 'discussion threads',
                'ordering': ('-is_pinned', '-last_reply_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='body')),
                ('is_trainer_response', models.BooleanField(default=False, verbose_name='from a trainer')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='hidden')),
                ('hidden_reason', models.CharField(blank=True, max_length=300, verbose_name='reason')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_hidden', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussions.thread')),
            ],
            options={
                'verbose_name': 'discussion reply',
                'verbose_name_plural': 'discussion replies',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['batch', '-created_at'], name='thread_batch_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['batch', 'is_pinned'], name='thread_pinned_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['thread', 'created_at'], name='reply_thread_order_idx'),
        ),
    ]
