# Generated by Django 5.2.17 on 2026-09-06 21:22

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(blank=True, default='', help_text='Signed at the foot of every email this system sends.', max_length=160, validators=[apps.common.validators.validate_no_control_characters], verbose_name='institution name')),
                ('support_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='support email')),
                ('support_phone', models.CharField(blank=True, default='', max_length=32, validators=[apps.common.validators.validate_no_control_characters], verbose_name='support phone')),
                ('notification_email_enabled', models.BooleanField(default=True, help_text='Turning this off suppresses delivery only. The in-app notification is still written, so nothing is lost.', verbose_name='send notification email')),
                ('export_retention_days', models.PositiveSmallIntegerField(default=14, help_text='How long a finished export stays downloadable before it expires.', verbose_name='keep exports for (days)')),
                ('resource_upload_max_mb', models.PositiveSmallIntegerField(default=25, help_text='Applies to course resources and assignment attachments.', verbose_name='largest upload (MB)')),
                ('singleton', models.BooleanField(default=True, editable=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'institution settings',
                'verbose_name_plural': 'institution settings',
                'constraints': [models.UniqueConstraint(fields=('singleton',), name='systemsetting_one_row')],
            },
        ),
    ]
