# Generated by Django 5.2.17 on 2026-08-31 10:56

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(editable=False, help_text='Human-readable identifier, e.g. GRS-S-00042. Allocated by the system.', max_length=20, unique=True, verbose_name='student ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('address_line1', models.CharField(blank=True, max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='address line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('country', models.CharField(blank=True, default='India', max_length=100, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('qualification', models.CharField(blank=True, choices=[('secondary', 'Secondary (10th)'), ('higher_secondary', 'Higher secondary (12th)'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's degree"), ('masters', "Master's degree"), ('other', 'Other')], max_length=32, verbose_name='highest qualification')),
                ('institution', models.CharField(blank=True, max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='college or institution')),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='graduation year')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='emergency contact name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[apps.common.validators.validate_phone_number], verbose_name='emergency contact phone')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, verbose_name='relationship')),
                ('guardian_name', models.CharField(blank=True, max_length=150, verbose_name='parent or guardian name')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, validators=[apps.common.validators.validate_phone_number], verbose_name='parent or guardian phone')),
                ('fee_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('waived', 'Waived'), ('overdue', 'Overdue')], db_index=True, default='pending', help_text='Administrator-maintained. Students see it but cannot change it.', max_length=16, verbose_name='fee status')),
                ('fee_status_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='fee status updated at')),
                ('notes', models.TextField(blank=True, help_text='Administrator-only. Never returned to the student.', verbose_name='internal notes')),
                ('fee_status_updated_by', models.ForeignKey(blank=True, help_text='Administrator who last changed the fee status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_status_updates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Deleting the account removes the profile; accounts are deactivated instead.', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student profile',
                'verbose_name_plural': 'student profiles',
                'ordering': ('student_id',),
                'indexes': [models.Index(fields=['fee_status', '-created_at'], name='student_fee_created_idx')],
            },
        ),
    ]
