# Generated by Django 5.2.17 on 2026-09-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('students', '0002_student_id_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The centre this student was admitted to. A later transfer may put their class at another one; this is where their record is kept.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='organisation.branch', verbose_name='branch'),
        ),
    ]
