# Generated by Django 5.2.17 on 2026-09-08 12:04

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In rupees. Decided by the counsellor or manager; students see it but cannot change it.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1000'))], verbose_name='agreed fee'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fee_amount_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fee amount updated at'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fee_amount_updated_by',
            field=models.ForeignKey(blank=True, help_text='Who last set the agreed fee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_amount_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution_kind',
            field=models.CharField(blank=True, choices=[('college', 'College'), ('employer', 'Employer')], help_text='Whether the institution named is where the student studies or works.', max_length=16, verbose_name='institution kind'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='college or employer'),
        ),
    ]
