# Generated by Django 5.2.17 on 2026-09-08 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_fee_amount_and_institution_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='The existing student who referred this one, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='students.studentprofile'),
        ),
    ]
