# Generated by Django 5.2.17 on 2026-09-08 13:20

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=120, validators=[apps.common.validators.validate_no_control_characters], verbose_name='designation'),
        ),
    ]
