# Generated by Django 5.2.17 on 2026-09-08 17:58

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, help_text="The student's roll or registration number at their college, if any.", max_length=32, validators=[apps.common.validators.validate_no_control_characters], verbose_name='roll number'),
        ),
    ]
