# Generated by Django 5.2.17 on 2026-09-12 11:29

import apps.common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0004_enrollment_is_upgrade_enrollment_transferred_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_amount', models.DecimalField(decimal_places=2, help_text='The course fee agreed with the student, in rupees, before any discount.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='agreed fee')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='discount')),
                ('discount_reason', models.CharField(blank=True, max_length=200, validators=[apps.common.validators.validate_no_control_characters], verbose_name='discount reason')),
                ('next_due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='next amount expected')),
                ('next_due_on', models.DateField(blank=True, null=True, verbose_name='expected by')),
                ('notes', models.TextField(blank=True, max_length=1000, validators=[apps.common.validators.validate_no_control_characters], verbose_name='notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_plans_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(help_text='The course this fee is for.', on_delete=django.db.models.deletion.PROTECT, related_name='fee_plan', to='enrollments.enrollment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_plans_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fee plan',
                'verbose_name_plural': 'fee plans',
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='receipt number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('paid_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='paid on')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=16, verbose_name='method')),
                ('reference', models.CharField(blank=True, help_text='A UPI or bank transaction id, a cheque number.', max_length=100, validators=[apps.common.validators.validate_no_control_characters], verbose_name='reference')),
                ('note', models.CharField(blank=True, max_length=300, validators=[apps.common.validators.validate_no_control_characters], verbose_name='note')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='voided at')),
                ('void_reason', models.CharField(blank=True, max_length=300, validators=[apps.common.validators.validate_no_control_characters], verbose_name='void reason')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments_voided', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.feeplan')),
            ],
            options={
                'verbose_name': 'fee payment',
                'verbose_name_plural': 'fee payments',
                'ordering': ('-paid_on', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='feeplan',
            index=models.Index(fields=['next_due_on'], name='feeplan_next_due_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['plan', 'voided_at'], name='feepayment_plan_live_idx'),
        ),
    ]
