/**
 * API calls for a student's own performance picture and the feedback written
 * about them.
 *
 * `apps.performance` (backend) is a newer app than the rest of this file's
 * siblings, and its two read endpoints used here have no typed shape yet in
 * `types/api.ts` — that file is generated by hand from the OpenAPI contract
 * and this slice has not been folded in. Rather than either guessing at a
 * shape or blocking the dashboard work on a second agent's file, the types
 * below are written directly from `apps/performance/engine.py` and
 * `apps/performance/serializers.py` (read, not modified, while building this).
 * When `types/api.ts` grows a real `StudentPerformanceEntry`/`Feedback` pair,
 * these should be deleted in favour of it — they are intentionally shaped to
 * be a drop-in match, field for field.
 *
 * Both endpoints are self-scoped and need no capability: `/performance/me/`
 * answers for whichever student profile the caller owns (or `[]` for anyone
 * without one), and `/performance/feedback/` returns only what
 * `apps.performance.access.visible_feedback` already resolves to the caller —
 * their own received feedback marked visible, nothing about anyone else. A
 * counsellor's session calling either would simply get `[]`; see
 * `apps/performance/access.py`'s docstring for why that capability is
 * deliberately absent from the counsellor role.
 */

import { apiFetch } from './api';

/** A single risk rule's verdict — mirrors `apps.performance.risk.RiskOutcome`. */
export interface PerformanceRiskOutcome {
  key: string;
  label: string;
  triggered: boolean;
  severity: 'none' | 'warning' | 'critical';
  detail: string;
  numbers: Record<string, unknown>;
}

/** The `risk` block of one performance entry — `apps.performance.risk.evaluate`'s output. */
export interface PerformanceRisk {
  at_risk: boolean;
  outcomes: PerformanceRiskOutcome[];
  triggered: string[];
  triggered_count: number;
}

/**
 * One enrolment's full standing, as `apps.performance.engine.student_performance`
 * returns it. Every numeric field is a real number or `null` — never `NaN` —
 * by that module's own stated contract, but this file's callers still run
 * every value through `lib/format.ts` rather than trust that at the type
 * level alone.
 */
export interface StudentPerformanceEntry {
  enrollment_id: string;
  course_title: string;
  batch_code: string;
  attendance: {
    percent: number | null;
    total_sessions: number;
    attended: number;
    has_records: boolean;
  };
  assessment: {
    average_percent: number | null;
    sitting_percent: number | null;
    recorded: number;
    total: number;
  };
  assignments: {
    percent: number | null;
    total: number;
    submitted: number;
    graded: number;
    passed: number;
    missed: number;
  };
  projects: { percent: number | null; required: number; finished: number };
  progress: { percent: number | null; expected_percent: number | null; variance: number | null };
  overall_score: number | null;
  risk: PerformanceRisk;
  counts: { components_measured: number; risk_flags: number };
}

/** A remark left about a student or a trainer — `apps.performance.models.Feedback`. */
export interface PerformanceFeedback {
  id: string;
  subject_type: 'student' | 'trainer';
  student: string | null;
  student_code: string | null;
  student_name: string | null;
  trainer: string | null;
  trainer_code: string | null;
  trainer_name: string | null;
  batch: string | null;
  batch_code: string | null;
  body: string;
  visible_to_subject: boolean;
  author: string | null;
  author_name: string | null;
  created_at: string;
}

/**
 * The caller's own performance, one entry per enrolment (most recent first,
 * matching the ordering `MyPerformanceView` builds its queryset with). `[]`
 * for a signed-in user who holds no student profile — never an error, since
 * that is simply "nothing to show" rather than a failure.
 */
export async function getMyPerformance(): Promise<StudentPerformanceEntry[]> {
  return apiFetch<StudentPerformanceEntry[]>('/api/v1/performance/me/');
}

/**
 * Feedback the caller may read about themself — from a trainer after a class,
 * or a manager's note, whichever the author marked visible to its subject.
 * Newest first. The API does not say which of "trainer" or "manager" wrote a
 * given line (`author_name` is a display string, not a role), so this module
 * cannot split the feed by author role; every entry is simply "feedback".
 */
export async function listMyFeedback(): Promise<PerformanceFeedback[]> {
  return apiFetch<PerformanceFeedback[]>('/api/v1/performance/feedback/');
}
