# Generated by Django 5.2.17 on 2026-09-06 18:15

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0004_alter_batch_options_alter_batchschedule_options_and_more'),
        ('students', '0002_student_id_sequence'),
        ('trainers', '0002_trainer_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('subject_type', models.CharField(choices=[('student', 'Student'), ('trainer', 'Trainer')], max_length=10, verbose_name='subject type')),
                ('body', models.TextField(max_length=5000, verbose_name='feedback')),
                ('visible_to_subject', models.BooleanField(default=True, verbose_name='visible to the subject')),
                ('author', models.ForeignKey(blank=True, help_text='Who wrote it. Null if that account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_written', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, help_text='The class this feedback relates to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='batches.batch')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='students.studentprofile')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
                'ordering': ('-created_at',),
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['student', '-created_at'], name='feedback_student_idx'), models.Index(fields=['trainer', '-created_at'], name='feedback_trainer_idx'), models.Index(fields=['batch', '-created_at'], name='feedback_batch_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('subject_type', 'student'), ('trainer__isnull', True)), models.Q(('student__isnull', True), ('subject_type', 'trainer'), ('trainer__isnull', False)), _connector='OR'), name='feedback_subject_matches_type')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('subject_type', models.CharField(choices=[('student', 'Student'), ('trainer', 'Trainer')], max_length=10, verbose_name='subject type')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 (serious concern) to 5 (excellent).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('strengths', models.TextField(blank=True, verbose_name='strengths')),
                ('concerns', models.TextField(blank=True, verbose_name='concerns')),
                ('actions', models.TextField(blank=True, verbose_name='agreed actions')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text="The engine's output at the moment this review was written. Frozen — never recomputed, even if the underlying records change later.", verbose_name='performance snapshot')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='Who wrote it. Null if that account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_reviews_written', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='students.studentprofile')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'performance review',
                'verbose_name_plural': 'performance reviews',
                'ordering': ('-period_end', '-created_at'),
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['student', '-period_end'], name='perfreview_student_idx'), models.Index(fields=['trainer', '-period_end'], name='perfreview_trainer_idx'), models.Index(fields=['reviewer', '-created_at'], name='perfreview_reviewer_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('subject_type', 'student'), ('trainer__isnull', True)), models.Q(('student__isnull', True), ('subject_type', 'trainer'), ('trainer__isnull', False)), _connector='OR'), name='performance_review_subject_matches_type'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='performance_review_period_ordered')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
