# Generated by Django 5.2.17 on 2026-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='next_review_at',
            field=models.DateField(blank=True, null=True, verbose_name='next review at'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='recommendations'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('probation', 'Probation'), ('ad_hoc', 'Ad hoc'), ('placement', 'Placement')], default='ad_hoc', max_length=30, verbose_name='review type'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='A free-form numeric score a reviewer assigns, separate from `rating`.', max_digits=4, null=True, verbose_name='score'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('shared', 'Shared'), ('acknowledged', 'Acknowledged')], default='draft', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='concerns',
            field=models.TextField(blank=True, help_text='Exposed to callers under both `concerns` and `weaknesses` — see `weaknesses`.', verbose_name='concerns'),
        ),
    ]
