# Generated by Django 5.2.17 on 2026-09-16 12:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0004_enrollment_is_upgrade_enrollment_transferred_to_and_more"),
        ("performance", "0002_review_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="level",
                    ),
                ),
                (
                    "triggered",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Rule keys currently triggered, e.g. ['attendance', 'assignments'].",
                        verbose_name="triggered rules",
                    ),
                ),
                (
                    "numbers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-rule numeric evidence: `{rule_key: {...}}`. See the class docstring.",
                        verbose_name="numbers",
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="computed at"
                    ),
                ),
                (
                    "previous_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="",
                        help_text="Empty until the second computation — there is no 'before' for the first. Never `null` on a `CharField` (DJ001); `''` is not a valid `RiskLevel` choice, so it cannot collide with a real, computed `RiskLevel.NONE` ('none').",
                        max_length=10,
                        verbose_name="previous level",
                    ),
                ),
                (
                    "previous_triggered",
                    models.JSONField(
                        blank=True, null=True, verbose_name="previously triggered rules"
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_state",
                        to="enrollments.enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "risk state",
                "verbose_name_plural": "risk states",
                "ordering": ("-computed_at",),
                "indexes": [
                    models.Index(fields=["level", "-computed_at"], name="riskstate_level_idx")
                ],
            },
        ),
    ]
