# Generated by Django 5.2.17 on 2026-09-16 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_riskstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskstate',
            name='manual_override',
            field=models.BooleanField(default=False, help_text="Set by automation's flag_risk action; not written by the risk engine.", verbose_name='manually flagged'),
        ),
        migrations.AddField(
            model_name='riskstate',
            name='manual_override_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='manual flag expires at'),
        ),
        migrations.AddField(
            model_name='riskstate',
            name='manual_override_level',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('warning', 'Warning'), ('critical', 'Critical')], default='', max_length=10, verbose_name='manually flagged level'),
        ),
        migrations.AddField(
            model_name='riskstate',
            name='manual_override_reason',
            field=models.TextField(blank=True, verbose_name='manual flag reason'),
        ),
        migrations.AddField(
            model_name='riskstate',
            name='manual_override_set_by',
            field=models.ForeignKey(blank=True, help_text="The automation rule's author of record for this flag (audit provenance).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
