# Generated by Django 5.2.17 on 2026-10-03 08:37

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0002_default_branch'),
        ('students', '0008_alter_studentprofile_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when the record was removed. Null means live.', null=True, verbose_name='deleted at')),
                ('delete_reason', models.CharField(blank=True, help_text='Why it was removed. Shown on the recovery screen.', max_length=255, verbose_name='reason for deletion')),
                ('full_name', models.CharField(max_length=120, verbose_name='full name')),
                ('mobile', models.CharField(max_length=20, verbose_name='mobile')),
                ('mobile_key', models.CharField(db_index=True, max_length=10, verbose_name='mobile key')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp number')),
                ('state', models.CharField(blank=True, max_length=60, verbose_name='state')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='city')),
                ('course', models.CharField(blank=True, max_length=60, verbose_name='course')),
                ('track', models.CharField(blank=True, max_length=60, verbose_name='track')),
                ('preferred_centre', models.CharField(blank=True, max_length=30, verbose_name='preferred centre')),
                ('mode', models.CharField(blank=True, max_length=20, verbose_name='mode of study')),
                ('batch_timing', models.CharField(blank=True, max_length=20, verbose_name='batch timing')),
                ('qualification', models.CharField(blank=True, max_length=40, verbose_name='qualification')),
                ('source', models.CharField(blank=True, max_length=40, verbose_name='source')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='UTM campaign')),
                ('remarks', models.TextField(blank=True, verbose_name='remarks')),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('counselling_booked', 'Counselling booked'), ('demo_booked', 'Demo class booked'), ('registered', 'Registered'), ('not_interested', 'Not interested'), ('not_eligible', 'Not eligible')], default='new', max_length=30, verbose_name='stage')),
                ('stage_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='stage changed at')),
                ('lost_reason', models.CharField(blank=True, max_length=40, verbose_name='lost reason')),
                ('lead_quality', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='lead quality')),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True, verbose_name='next follow-up')),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='last contacted')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisation.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Who removed it. Null if the account has since been removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'enquiry',
                'verbose_name_plural': 'enquiries',
                'ordering': ('-created_at',),
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['branch', 'stage'], name='enquiry_branch_stage_idx'), models.Index(fields=['owner', 'stage'], name='enquiry_owner_stage_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
